<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_fixedasset;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Add Fixed Asset Name</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td><?php echo $tr->translate("Asset Name")?></td>
							<td><?php echo $frm->getElement('asset_name');?></td>
							<td><?php echo $tr->translate("Asset Type")?></td>
							<td><?php echo $frm->getElement('asset_type');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Asset cost")?></td>
							<td><?php echo $frm->getElement('asset_cost')?></td>
							<td><?php echo $tr->translate("Useful life")?></td>
							<td><?php echo $frm->getElement('usefull_life');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Salvage value")?></td>
							<td><?php echo $frm->getElement('salvage_value')?></td>		
							<td><?php echo $tr->translate("Payment method")?></td>
							<td><?php echo $frm->getElement('payment_method')?></td>					
						</tr>
						<tr>
							<td><?php echo $tr->translate("Date")?></td>
							<td><?php echo $frm->getElement('date')?></td>		
							<td><?php echo $tr->translate("Branch")?></td>
							<td><?php echo $frm->getElement('branch')?></td>					
						</tr>
					</table>
					</fieldset>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
