<?php 
	  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
	
	  $home=$this->url(array('module'=>'home','controller'=>'index','action'=>'index'), null, true);
	  $transfer=$this->url(array('module'=>'transfer','controller'=>'index','action'=>'index'), null, true);
	  $partner=$this->url(array('module'=>'partner','controller'=>'index','action'=>'index'), null, true);
	  $exchange=$this->url(array('module'=>'exchange','controller'=>'index','action'=>'index'), null, true);
	  $reports=$this->url(array('module'=>'report','controller'=>'index','action'=>'index'), null, true);
	  $accounting=$this->url(array('module'=>'accounting','controller'=>'index','action'=>'index'), null, true);
	  $capital=$this->url(array('module'=>'capital','controller'=>'index','action'=>'index'), null, true);
	  $expend_view=$this->url(array('module'=>'expend','controller'=>'index','action'=>'index'), null, true);
	  $payroll_view=$this->url(array('module'=>'payroll','controller'=>'index','action'=>'index'), null, true);
	  $backup=$this->url(array('module'=>'backup','controller'=>'index','action'=>'index'), null, true);
      $user=$this->url(array('module'=>'user','controller'=>'index','action'=>'index'), null, true);
      $acl=$this->url(array('module'=>'rsvAcl','controller'=>'index','action'=>'index'), null, true);
      $logout=$this->url(array('module'=>'default','controller'=>'index','action'=>'logout'), null, true);
      $logout=$this->url(array('module'=>'inserttable','controller'=>'index','action'=>'index'), null, true);
      $keeping=$this->url(array('module'=>'Keeping','controller'=>'index','action'=>'index'), null, true);
	  $module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	  $item_arr=array(
		'index'=>'<li class="link">
							<a title="ទំព័រដើម" href="'.$home.'">
								<span>'.$tr->translate("ទំព័រដើម").'</span>
							</a>
						</li>',
	  	'partner'=>'<li class="link">
			  		<a title="ដៃគូសហការ" href="'.$partner.'">
			  		<span>'.$tr->translate("ដៃគូសហការ").'</span>
			  		</a>
			  		</li>',
	  	'group'=>'<li class="link">
						<a title="សេវាផ្ងើប្រាក់" href="'.$transfer.'">
							<span>'.$tr->translate("សេវាផ្ងើប្រាក់").'</span>
						</a>
					</li>',
	    'loan'=>'<li class="link">
						<a title="សេវាប្តូរប្រាក់" href="'.$exchange.'">
							<span>'.$tr->translate("សេវាប្តូរប្រាក់").'</span>
						</a>
					</li>',	 
	  	'expend'=>'<li class="link">
		  		<a title="កំណត់ដើមទុន" href="'.$capital.'">
		  		<span>'.$tr->translate("កំណត់ដើមទុន").'</span>
		  		</a>
	  		</li>',
	  	'payroll'=>'<li class="link">
		  		<a title="ព័ត៏មានប្រាក់ខែ" href="'.$payroll_view.'">
		  			<span>'.$tr->translate("ប្រាក់ខែបុគ្គលិក").'</span>
		  		</a>
	  		</li>',
	  	'keeping'=>'<li class="link">
	  		<a title="keeping" href="'.$keeping.'">
	  			<span>'.$tr->translate("KEEPING").'</span>
	  		</a>
	  		</li>',
	  	'report'=>'<li class="របាយការណ័">
			  		<a title="Report" href="'.$reports.'">
			  			<span>'.$tr->translate("របាយការណ័").'</span>
			  		</a>
			  		</li>',
	    'allreport'=>'<li class="គណនេយ្យ">
						<a title="Report" href="'.$accounting.'">
							<span>'.$tr->translate("គណនេយ្យ").'</span>
						</a>
					   </li>',
	  	'rsvAcl'=>'<li class="link">
			  		<a title="acl" href="'.$acl.'">
			  			<span>'.$tr->translate("Module Mg").'</span>
			  		</a>
			  		</li>',
	    'backup'=>'<li class="link">
						<a title="BACKUP DATABASE" href="'.$backup.'">
							<span>'.$tr->translate("BACKUP DB").'</span>
						</a>
					 </li>',	  
	  
	  'logout'=>'<li class="link">
	  		<a title="USER" href="'.$logout.'">
	  		<span>'.$tr->translate("LOGOUT").'</span>
	  		</a>
	  		</li>',
	  );
?>  
<div id="menu">
	<ul>
		<?php
			foreach($item_arr as $key=>$value){
				if($module==$key){
					echo str_replace('class="link"', 'class="current"', $value);
				}
				else{
					echo $value;
				}
			} 
		?>
	</ul>
</div>