	<?php
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
		/*--------------------URLs link display--------------------------*/
		  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
		$arr_param_menu=array( 
			'home'=>array(
						'index'=>'<li><a href="">'.$tr->translate("HOME").'</a></li>',
			),
			'partner'=>array(
				'index'=>'<li><a href="" title="">'.$tr->translate("ដៃគូសហការ").'</a></li>',
				'deposite'=>'<li><a href="" title="">'.$tr->translate("ដាក់សាច់ប្រាក់").'</a></li>',
				'withdraw'=>'<li><a href="" title="">'.$tr->translate("ដកប្រាក់").'</a></li>',
			),
			'Keeping'=>array(
// 					'Outmoney/index'=>'<li><a href="" title="">'.$tr->translate("ដកប្រាក់").'</a></li>',
// 					'newput/index'=>'<li><a href="" title="">'.$tr->translate("NEW INPUT").'</a></li>',
// 					'Putmoney/index'=>'<li><a href="" title="">'.$tr->translate("Salary").'</a></li>',
					'index/index'=>'<li><a href="" title="">'.$tr->translate("ដាក់ប្រាក់").'</a></li>',
					
				
			),
			'transfer'=>array(
						'index'=>'<li><a href="" title="">'.$tr->translate("វេសាច់ប្រាក់").'</a></li>',
						'fund'=>'<li><a href="" title="">'.$tr->translate("សងប្រាក់").'</a></li>',
			),
			'exchange'=>array(
						'index'=>'<li><a href="" title="">'.$tr->translate("ប្តូប្រាក់").'</a></li>',
						'exchangrate'=>'<li><a href="" title="">'.$tr->translate("អត្រាការប្រាក់").'</a></li>',
						'showrate'=>'<li><a href="" title="">'.$tr->translate("ពិនិតមើលកាប្រាក់").'</a></li>',
				),
			'capital'=>array(
						'Index'=>'<li><a href="" title="">'.$tr->translate("ដាក់ប្រាក់").'</a></li>',
						'Cash'=>'<li><a href="" title="">'.$tr->translate("អត្រាការប្រាក់").'</a></li>',
						'Stock'=>'<li><a href="" title="">'.$tr->translate("ពិនិតមើលកាប្រាក់").'</a></li>',
				),
			'payroll'=>array(
						'add'=>'<li><a href="" title="">'.$tr->translate("ប្រាក់ខែរគោល").'</a></li>',
						),
			'reports'=>array(
								'index'=>'<li><a href="" title="">'.$tr->translate("របាយការណ៏").'</a></li>',
					             
				),
			'accounting'=>array(
						'income'=>'<li><a href="" title="">'.$tr->translate("ចំណូល").'</a></li>',
						'expense'=>'<li><a href="" title="">'.$tr->translate("ចំណាយ").'</a></li>',
						'index'=>'<li><a href="" title="">'.$tr->translate("ផ្សេងៗ").'</a></li>',
				),
			'loan'=>array(
						'index'=>'<li><a href="" title="">'.$tr->translate("កម្ចី").'</a></li>',
						'fund'=>'<li><a href="" title="">'.$tr->translate("សងប្រាក់").'</a></li>',
				),
			'tellerandexchange'=>array(
						'teller'=>'<li><a href="">'.$tr->translate("កន្លែងបង់ប្រាក់").'</a></li>',
						'exchanges'=>'<li><a href="">'.$tr->translate("សេវាប្តូរប្រាក់").'</a></li>',
						'xchange'=>'<li><a href="">'.$tr->translate("សេវាប្តូរប្រាក់").'</a></li>',
						'showrate'=>'<li><a href="">'.$tr->translate("ពិនិត្យអាត្រាប្តូរប្រាក់").'</a></li>',
						'Spread'=>'<li><a href="">'.$tr->translate("កំណត់អាត្រាប្តូរប្រាក់").'</a></li>',
				
				
				),
				'test'=>array(
						'index'=>'<li><a href="" title="">'.$tr->translate("Test").'</a></li>',
						'add'=>'<li><a href="" title="">'.$tr->translate("trant").'</a></li>',
						'views'=>'<li><a href="" title="">'.$tr->translate("start").'</a></li>',
				),
		); 
	?>
	<div id="header-left">
	<ul>
			<?php 
// 				$request=Zend_Controller_Front::getInstance()->getRequest();
				$dc=new Application_Model_Decorator();					
				$class="current-left";					
				$menu=$dc->getMenuLeft($arr_param_menu[$request->getModuleName()],$request->getControllerName(),$request->getModuleName());
				if($menu) echo $menu;					
			?>
	</ul>																
	</div>