<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;
?>
<!DOCTYPE html>
<html >
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
.td{width:179px !important;}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'capital-transfer','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="POST" enctype="application/x-www-form-urlencoded" onload="getAmountFrom();getAmountTo();">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<!-- <table cellspacing="10"> -->
<!-- 	<tr> -->
<!-- 		<td> -->
				<fieldset>
					<legend><strong>សំណុំបែបបទផ្ទេរប្រាក់</strong></legend>
					<table cellspacing="10"  width="100%">
						<?php //echo $frm->getElement('id');?>
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះបុគ្គលិក")?></td>
							<td class="td"><?php echo $frm->getElement('user_from')?></td>
							<td>ប្រាក់ដុល្លា</td>
							<td><?php echo $frm->getElement('usa_from')?></td>
							<td>ប្រាក់បាត</td>	
							<td><?php echo $frm->getElement('bath_from')?></td>
							<td>ប្រាក់រៀល</td>
							<td><?php echo $frm->getElement('reil_from')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះបុគ្គលិក")?></td>
							<td><?php echo $frm->getElement('user_to')?></td>
							<td>ប្រាក់ដុល្លា</td>
							<td><?php echo $frm->getElement('usa_to')?></td>
							<td>ប្រាក់បាត</td>	
							<td><?php echo $frm->getElement('bath_to')?></td>
							<td>ប្រាក់រៀល</td>
							<td><?php echo $frm->getElement('reil_to')?></td>
						</tr>
						<tr>
							<td>Date</td>	
							<td><?php echo $frm->getElement('date')?></td>
							<td>ប្រាក់ដុល្លា</td>
							<td><?php echo $frm->getElement('usa')?></td>
							<td>ប្រាក់បាត</td>	
							<td><?php echo $frm->getElement('bath')?></td>
							<td>ប្រាក់រៀល</td>
							<td><?php echo $frm->getElement('reil')?></td>
							
						</tr>
						<tr>
							<td>Status</td>
							<td><?php echo $frm->getElement('status')?></td>
							<td>Note</td>
							<td colspan="3"><?php echo $frm->getElement('note');?></td>
							<td></td>
							<td></td>
							
						</tr>
						
					</table>
				</fieldset>
<!-- 				<td align="center"> -->
		<center><input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</center>	
<!-- 		</td> -->
<!-- 		</td> -->
<!-- 	</tr>		 -->
<!-- 	<tr> -->
<!-- 		<td align="center"> -->
<!-- 			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" -->
<!-- 				 iconClass="dijitEditorIcon dijitEditorIconSave"/> -->
<!-- 		</td> -->
<!-- 	</tr>	 -->
<!-- </table> -->
</form>
</html>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.DateTextBox");

function validateTransfer(type){
	//alert(type);
	if(type==1){
		var usa = dijit.byId('usa').get('value');
		var usa_from = dijit.byId('usa_from').get('value');
		//alert(usa);
		//alert(usa_from);
		if(usa > usa_from){
			alert("Money transfer is not enought");
			dijit.byId('usa').attr('value',usa_from);
		}
	}

	if(type==2){
		var bath = dijit.byId('bath').get('value');
		var bath_from = dijit.byId('bath_from').get('value');
		//alert(usa);
		//alert(usa_from);
		if(bath > bath_from){
			alert("Money transfer is not enought");
			dijit.byId('bath').attr('value',bath_from);
		}
	}

	if(type==3){
		var riel = dijit.byId('reil').get('value');
		var riel_from = dijit.byId('reil_from').get('value');
		//alert(usa);
		//alert(usa_from);
		if(riel > riel_from){
			alert("Money transfer is not enought");
			dijit.byId('reil').attr('value',riel_from);
		}
	}
}
var getAmount ='<?php echo $this->url(array('module'=>'capital','controller'=>'transfer','action'=>'get-capital'));?>'; 
function getAmountFrom(){
	
	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'user_id':dijit.byId('user_from').get('value'),
		},	
		handleAs:"json",
		load: function(data) {
			 //alert(data);
			 tmp = dojo.fromJson(data);	
			 for(var i=0; i< tmp.length; i++){
				 alert(tmp[i]);
				 //alert(a);
		    	  //if(tmp[i].currency_id==1){
		    		//  dijit.byId('usa_from').attr('value',tmp[i].amount);
			      //}else if(tmp[i].currency_id==2){
			    	 // dijit.byId('bath_from').attr('value',tmp[i].amount);
			      //}else if(tmp[i].currency_id==3){
			    	//  dijit.byId('reil_from').attr('value',tmp[i].amount);
			      //}
	    	  }
			/*if(dijit.byId('usa_from').attr('value',data.currency_id)==1){
				dijit.byId('bath_from').attr('value',0);
				dijit.byId('reil_from').attr('value',0);
			    dijit.byId('usa_from').attr('value',data.amount);
			 }else if(dijit.byId('bath_from').attr('value',data.currency_id)==2){
				dijit.byId('usa_from').attr('value',0);
				dijit.byId('reil_from').attr('value',0);
			    dijit.byId('bath_from').attr('value',data.amount);
			    }
			else if(dijit.byId('reil_from').attr('value',data.currency_id)==3){
				dijit.byId('usa_from').attr('value',0);
				dijit.byId('bath_from').attr('value',0);
				dijit.byId('reil_from').attr('value',data.amount);
				}*/
			//dijit.byId('reil_from').attr('value',data.amount_riel);
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}

function getAmountTo(){

	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'brance_id':dijit.byId('user_to').get('value'),
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('usa_to').attr('value',data.amount_dollar);
			dijit.byId('bath_to').attr('value',data.amount_bath);
			dijit.byId('reil_to').attr('value',data.amount_riel);
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}
</script>
