<?php
	$this->headTitle('Currency Smart | Report Fund Transaction'); 
	echo $this->headTitle();
// 	print_r($this->listowe);exit();
// 	echo $this->fundlist[1]['capital_bath']."test";
?>	
<style>
.style-bold{font-weight: bold;}
</style>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.form.DateTextBox");

	 var sender_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->senderlist));?> );  
	
	function doPrint(div_id) {
		window.frames["print_frame"].document.body.innerHTML = dojo.byId('grid_'+ div_id).innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    confirmSubmit(div_id);	
	    	    
	}
	function confirmSubmit(div_id){
		/*if (confirm("តើ​អ្នកជំពាក់នេះពិតជាបានសងរួចហើយរឺទេ ?")){
			dijit.byId('frmlist_fn_rpt_'+ div_id).submit();			
		}*/
	}
</script>
<script type="text/javascript">
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
            store: sender_store,
            autoComplete: true,                        
            required: true,
            id: "sender_name",
            name: "sender_name",
            searchAttr: "name",
            value: "<?php echo $this->selected;?>",     
            class: 'fullside',            
            missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
            onChange: function() {                
            }
        }, "sender_name");
	}); 

</script>
<form name="frmlist_fund" action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rpt-fundtran')); ?>" dojoType="dijit.form.Form" method="post">
	<table width="100%" style=" border-top: 1px solid #000; border-bottom: 1px solid #000; padding: 10px 0 10px 0;">
		<tr>
		    <td width="25%">  	
				<input id="sender_name" />	
		    </td>
		    <td width="35%">  	
		    </td>
		    <td width="20%" align="right"> 
		    	ពី៖&nbsp;
				<input type="text" name="from_date" id="from_date" value="<?php echo date_format(date_create($this->from_date), "Y-m-d");?>"
					dojoType="dijit.form.DateTextBox" style="height: 30px; width: 210px;" 
					rangeMessage="កាល​បរិច្ឆេទ  ពី មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ដល់"
					constraints="{datePattern:'dd/MM/yyyy', max:'<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>'}" 
					onchange="dijit.byId('to_date').constraints.min = arguments[0]; " /> 	
		    </td>
		    <td width="20%" align="right"> 
		    	ដល់៖&nbsp;
				<input type="text" name="to_date" id="to_date" value="<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>" 
				dojoType="dijit.form.DateTextBox" style=" height: 30px; width: 195px;"
				rangeMessage='កាល​បរិច្ឆេទ  ដល់ មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ពី' 
				constraints="{min:'<?php echo date_format(date_create($this->from_date), "Y-m-d");?>', datePattern:'dd/MM/yyyy'}" 
				onChange="dijit.byId('from_date').constraints.max = arguments[0]; " /> 	
		    </td>
		</tr><tr style="height: 60px;">
		    <td colspan="4" align="right"> 
		    <input type="submit" value="ស្វែង​រក" label="ស្វែង​រក" id="submitButton" 
						dojoType="dijit.form.Button"  iconClass="dijitIconSearch"/> 	
		    </td>
		</tr>
	</table>
</form>
<br/>

<?php if(!empty($this->fundlist['err']) && $this->fundlist['err']){?>
	<script type="text/javascript">
		alert("<?php echo $this->fundlist['msg']?>");
	</script>
	<table style="width: 100%; line-height: 25px;">		
		<tr>
			<td colspan="2" style="color: red; text-align: center;">
				<br/><br/>
				<?php echo $this->fundlist['msg']?>
			</td>
		</tr>
	</table>
	<br/><br/><br/>
<?php }else{#sopharat test report;?>

<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
	showLabel="false" type="button" onclick="doPrint('1');">Print</button><br/>
<div id="grid_1" style="border:1px solid #000;" >
	<center>បញ្ជីទូទាត់សងប្រាក់គិតត្រឹមថ្ងៃ <?php echo $this->from_date." ដល់ថ្ងៃទី ".$this->to_date;?></center><br/>
<table border = 1; style="width: 100%;float:right; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
		<tr class="bgtop" align="center">
			<td><b style="font-size: 13px;">&nbsp;ល.រ&nbsp;</b></td>
			<td><b style="font-size: 13px;">&nbsp;ឈ្មោះអ្នកជំពាក់&nbsp;</b></td>
			<td><b style="font-size: 13px;">&nbsp;លេខប្រតិបត្តិការណ៏&nbsp;</b></td>
			<td><b style="font-size: 13px;">&nbsp;ថ្ងែខែសង&nbsp;</b></td>
			<td><b style="font-size: 13px;">&nbsp;រូបិយប័ណ្ណ&nbsp;</b></td>
			<td><b style="font-size: 13px;">&nbsp;ប្រាក់ជំពាក់&nbsp;</b></td>
			<td><b style="font-size: 13px;">&nbsp;ប្រាក់សង&nbsp;</b></td>
			<td><b style="font-size: 13px;">&nbsp;ប្រាក់នៅសល់&nbsp;</b></td>
			<td><b style="font-size: 13px;">&nbsp;ផ្សេងៗ&nbsp;</b></td>
		</tr>
		<?php 
		    $db_payment = new Application_Model_DbTable_DbPayment();
			$tmp_sender='';
			$i=0;
			if(!empty($this->fundlist)){  
			  $row_funddate = '';$row_owe = '';$row_sender='';
			  $row_beforepay = '';
			  foreach ( $this->fundlist as $key => $tran) {
// 				print_r($tran);echo "<br/>";
				#if ($tmp_sender !== $ower){
				if($tmp_sender!=$tran['sender_id']){$i++;}
				$bg="#FFF";
// 				if($i%2==0){$bg="#dfdfe0";}
				
				$rowspan = 1;
				if($tmp_sender!=$tran['sender_id']){
// 					echo 2222;
					$owe=$row_funddate==''?'':'<tr align="center" style="background:#fffdd3;"><td colspan="9"><b>ជំពាក់</b></td></tr>';
					$pay=$row_funddate==''?'':'<tr align="center" style="background:#e5fff0;"><td colspan="9"><b>សង</b></td></tr>';
					echo $row_sender.$owe.$row_owe.$row_beforepay.$pay.$row_funddate;
					$row_owe = '';
					$k=1;$p=1;
					$row_sender = '<tr style="background: #dfdfe0;"><td colspan="9">&nbsp;</td></tr>
					<tr align="center" style="background:'.$bg.'">
						<td><span style="color:red;">'.$i.'</span></td>
						<td style="font-size:13px;"><b>'.$tran['sender_name'].'</b></td>
						<td colspan="7"></td>
					</tr>';
            		$row_funddate = '<tr align="center" style="background:'.$bg.'">
            			<td colspan="2" style="text-align: right; padding-right:10px;"><span style="color:green;">'.$k.'</span></td>
						<td>'.$tran['invoice_found'].'</td>
						<td>'.$tran['date_refund'].'</td>
            			<td colspan="5"></td>
            		</tr>';
// 					$tmp_sender = $tran['sender_id'];
					
					//transfer befor payment
					$owe_before = $db_payment->getTransactionOweByIdBeforPayment($tran['sender_id'],$this->from_date,$this->to_date);
					$row_beforepay = '';
					if(!empty($owe_before)){
						foreach ($owe_before as $ine=>$d){
							$cur_txt = '($) ដុល្លា';
							if($d['amount_type']==2){
								$cur_txt = '(฿) បាត';
							}else if($d['amount_type']==3){
								$cur_txt = '(៛) រៀ់ល';
							}
							$row_beforepay .= '<tr align="center" style="background:'.$bg.'">
								<td colspan="2" style="text-align: right; padding-right:10px;"><span style="color:blue;">'.$p.'</span></td>
								<td>'.$d['invoice_no'].'</td>
								<td>'.$d['send_date'].'</td>
								<td style="font-size:13px;">'.$cur_txt.'</td>
								<td>'.number_format($d['total_money'],2).'</td>
								<td>-</td>
								<td>-</td>
								<td></td>
							</tr>';$p++;
						}
					}
				}else{
					
					$k +=1;
					$row_funddate .= '<tr align="center" style="background:'.$bg.'">
            			<td colspan="2" style="text-align: right; padding-right:10px;"><span style="color:green;">'.$k.'</span></td>
						<td>'.$tran['invoice_found'].'</td>
						<td>'.$tran['date_refund'].'</td>
            			<td colspan="5"></td>
            		</tr>';
				}
				$tmp_sender = $tran['sender_id'];

				$row_d = '';
				if($tran['refund_dollar']!=0){
					$row_d = '
	 					<td style="font-size:13px;">($) ដុល្លា</td>
						<td>'.number_format($tran['capital_dollar'],2).'</td>
						<td>'.number_format($tran['refund_dollar'],2).'</td>
						<td>'.number_format($tran['capital_dollar']-$tran['refund_dollar'],2).'</td>
						<td></td>
					</tr>';
				}
				if($tran['refund_bath']!=0){
					$row_d .= '<tr align="center" style="background:'.$bg.'">
	 					<td style="font-size:13px;">(฿) បាត</td>
						<td>'.number_format($tran['capital_bath'],2).'</td>
						<td>'.number_format($tran['refund_bath'],2).'</td>
						<td>'.number_format($tran['capital_bath']-$tran['refund_bath'],2).'</td>
						<td></td>
					</tr>';
					$rowspan++;
				}
				if($tran['refund_riel']!=0){
					$row_d .= '<tr align="center" style="background:'.$bg.'">
						<td style="font-size:13px;">(៛) រៀ់ល</td>
						<td>'.number_format($tran['capital_riel'],2).'</td>
						<td>'.number_format($tran['refund_riel'],2).'</td>
						<td>'.number_format($tran['capital_riel']-$tran['refund_riel'],2).'</td>
						<td></td>
					</tr>';
					$rowspan++;
				}
				
				$row_funddate .= '<tr align="center" style="background:'.$bg.'">
									<td colspan="4" rowspan="'.$rowspan.'"><span style="font-size:13px; font-weight:bold;">ប្រាក់ក្រោយទូទាត់</span></td>'.$row_d;
				
				$trandebt_dollar = null;$trandebt_bath=null;$trandebt_riel=null;
				if($tran['trandebt_dollar']!=0){
					$trandebt_dollar = $db_payment->getTransactionOweByIdForreport($tran['trandebt_dollar']);
					foreach ($trandebt_dollar as $index=>$data){
						$row_owe .= '<tr align="center" style="background:'.$bg.'">
							<td colspan="2" style="text-align: right; padding-right:10px;"><span style="color:blue;">'.$p.'</span></td>
							<td>'.$data['invoice_no'].'</td>
							<td>'.$data['send_date'].'</td>
							<td style="font-size:13px;">($) ដុល្លា</td>
							<td>'.number_format($data['total_money'],2).'</td>
							<td>-</td>
							<td>-</td>
							<td></td>
						</tr>';$p++;
					}
				}
				if($tran['trandebt_bath']!=0){
					$trandebt_bath = $db_payment->getTransactionOweByIdForreport($tran['trandebt_bath']);
					foreach ($trandebt_bath as $index=>$data){
						$row_owe .= '<tr align="center" style="background:'.$bg.'">
							<td colspan="2" style="text-align: right; padding-right:10px;"><span style="color:blue;">'.$p.'</span></td>
							<td>'.$data['invoice_no'].'</td>
							<td>'.$data['send_date'].'</td>
							<td style="font-size:13px;">(฿) បាត</td>
							<td>'.number_format($data['total_money'],2).'</td>
							<td>-</td>
							<td>-</td>
							<td></td>
						</tr>';$p++;
					}
				}
				if($tran['trandebt_riel']!=0){
					$trandebt_riel = $db_payment->getTransactionOweByIdForreport($tran['trandebt_riel']);
					foreach ($trandebt_riel as $index=>$data){
						$row_owe .= '<tr align="center" style="background:'.$bg.'">
							<td colspan="2" style="text-align: right; padding-right:10px;"><span style="color:blue;">'.$p.'</span></td>
							<td>'.$data['invoice_no'].'</td>
							<td>'.$data['send_date'].'</td>
							<td style="font-size:13px;">(៛) រៀ់ល</td>
							<td>'.number_format($data['total_money'],2).'</td>
							<td>-</td>
							<td>-</td>
							<td></td>
						</tr>';$p++;
					}
				}
				
// 			if(count($this->fundlist)==1){
				$owe=$row_funddate==''?'':'<tr align="center" style="background:#fffdd3;"><td colspan="9"><b>ជំពាក់ពីមុន</b></td></tr>';
				$pay=$row_funddate==''?'':'<tr align="center" style="background:#e5fff0;"><td colspan="9"><b>បានសង</b></td></tr>';
				echo $row_sender.$owe.$row_owe.$row_beforepay.$pay.$row_funddate;
// 			}else{
				//echo $row_sender;
// 			}
				
		}// end foreach
	}//end if
		?>	
	</table>
</div>
<iframe marginwidth="45" marginheight="45" name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>

<?php }?>