<?php
	$this->headTitle('Currency Smart | Report Current Balance page'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$session_user=new Zend_Session_Namespace('auth');
?>	
<style>
<!--
	.tbtable{		
		font-weight: bolder;
		line-height: 40px;
		text-align: center;
	}
	.tbtable .tbheader{
		background-color: #012a15;
		text-align: left;
		color: #fff;
	}
	.tbtable .first{
		background-color: #016315;
		color: #fff;
	}
	.tbtable .first td{
		width: 33.33%
	}
	.tbtable .second{
		background-color: #fff; 
		color: black;
	}
	.nevg-value{
		color: RED;
	}
	.tbtable .second .input-inner {
		margin: 0px;
		padding: 0px;
		width: 99%;	
		border: none;
	}
	
	#dollar.dijitInputInner, #bath.dijitInputInner, #rail.dijitInputInner{
		text-align: center;		
		background-color: #FFFFFF !important;
	}
	
	.bg-white{
		background-color: #FFFFFF !important;		
	}
}
-->
</style>
<?php if($session_user->level == 1): //Admin View Only?>
<form id='frm_search_capital' action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rptbalance')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<label>ឈ្មោះ​អ្នក​ប្រើប្រាស់</label>
	<select style="text-align: left;" onchange="dijit.byId('frm_search_capital').submit();" name="user_id" id="select_user_id" dojoType="dijit.form.FilteringSelect" required="true"> 
		<?php foreach ($this->users as $key => $u) : ?>
			<option value="<?php echo $u['id'];?>" <?php echo ($u['id'] == $this->user_id)?"selected":"";?>><?php echo  $u['name'];?></option>
		<?php endforeach;?> 
	</select>
	
	
	<select style="text-align: left; float: right;" onchange="dijit.byId('frm_search_capital').submit();" name="month" id="select_month" dojoType="dijit.form.FilteringSelect" required="true"> 
		<?php for($i=1; $i <=12; $i++ ) : ?>
			<option value="<?php echo $i;?>" <?php echo ($i == $this->month)?"selected":"";?>><?php echo  $i;?></option>
		<?php endfor;?> 
	</select> 
	<label style="float: right;">ព័ត៌មាន​អំពី ​ដើមទុន ខែ: </label>
	
	<input type="hidden" name="actions" value="search">
</form>
<?php endif;?>

<form id='frm_add_capital' action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rptbalance')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('doloar').get('value') == 0 && dijit.byId('bath').get('value') == 0 && dijit.byId('rail').get('value') == 0){
					dijit.byId('doloar').focus();
					return false;
				}

				return true;
			} else {
				return false;
			}
	</script>	 
	
	<table class="tbtable" style="margin:10px auto; width:100%;">
		<tr class="tbheader">
			<td>&nbsp;ដើមទុនបច្ចុប្បន្ន</td>
		</tr>
		<tr>
			<td>	
				<table cellspacing='0' border="1" style="width: 100%;">									
					<tr class="first">
						<td>ដុល្លា $</td>
						<td>បាត B</td>
						<td>រៀល R</td>
					</tr>
					<tr class="second">
						<td <?php echo ($this->balance['dollar'] <0)?"class='nevg-value'":"";?>>
							<?php echo number_format($this->balance['dollar'], (strpos($this->balance['dollar'], "."))?2:0);?>
						</td>
						<td <?php echo ($this->balance['bath'] <0)?"class='nevg-value'":"";?>>
							<?php echo number_format($this->balance['bath'], (strpos($this->balance['bath'], "."))?2:0);?>
						</td>
						<td <?php echo ($this->balance['rail'] <0)?"class='nevg-value'":"";?>>
							<?php echo number_format($this->balance['rail'], (strpos($this->balance['rail'], "."))?2:0);?>
						</td>
					</tr>									
				</table>	
			</td>
		</tr>
		<?php if($session_user->level == 1): //Admin Upadte Only?>
		<tr>
			<td>	
				<table cellspacing='0' border="1" style="width: 100%;">									
					<tr class="first">
						<td>ដុល្លា $</td>
						<td>បាត B</td>
						<td>រៀល R</td>
					</tr>
					<tr class="second bg-white">
						<td>
							<input type="text" name="dollar" id="dolar"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'dollar',
									id:'dollar',	
									class:'input-inner',								
									value:0,
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
						</td>
						<td>
							<input type="text" name="bath" id="bath"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'bath',
									id:'bath',									
									value:0,
									class:'input-inner',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
						</td>
						<td>
							<input type="text" name="rail" id="rail"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'rail',
									id:'rail',									
									value:0,
									class:'input-inner',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
						</td>
					</tr>									
				</table>	
			</td>
		</tr>
		<tr>
			<td align="right">  
				<input type="reset" value="សំអាត" label="សំអាត" id="busyButton" dojoType="dijit.form.Button"/>
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" />				 
			</td>
		</tr>
		<?php endif;?>
	</table>
	<input type="hidden" name="user_id" value="<?php echo $this->user_id;?>">
	<input type="hidden" name="actions" value="add_capital">
</form>
<?php if(!empty($this->tranlist['err']) && $this->tranlist['err']):?>
	<script type="text/javascript">
	<!--
		alert("<?php echo $this->tranlist['msg']?>");
	//-->
	</script>
	<style>
		.table_print{
			width: 100%; 
			line-height: 40px;
			font-size:12pt; 
		}
		.header{
			font-size: 16pt;
			font-weight: bolder;
			text-align: center;
		}
	</style>
	<table class="table_print">
		<tr>
			<td class="header">របាយការណ៍ ដើម​ទុន</td>
		</tr>
		<tr>
			<td style="color: red; text-align: center;">
				<br/><br/>
				<?php echo $this->tranlist['msg']?>
			</td>
		</tr>
	</table>
	<br/><br/><br/>
<?php else:?>
<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
	showLabel="false" type="button" onclick="doPrint();">Print</button><br/>
<div id="grid" >
	<style>
		.lblname{
			padding-left: 20px;
		}
		.header{
			font-size: 16pt;
			font-weight: bolder;
			text-align: center;
		}
		.table_print{
			width: 100%; 
			line-height: 40px;
			font-size:12pt; 
		}
		.table_print table{
			width: 100%; 
		}
		.table_print table th{
			font-weight: bolder;
			text-align: center;
		}
		.table_print table th.date{
			width: 15%;
		}
		
		.table_print table th{
			width: 28.33%;
		}
		
		.table_print table td.date{
			text-align: left;
			padding-left: 10px;
		}
		
		.table_print table td{
			text-align: center;
		}
	</style>
	<table class="table_print">
		<tr>
			<td class="header">របាយការណ៍ ដើម​ទុន</td>
		</tr>
		<tr>
			<td colspan="2">
				<?php $l_name = $this->tranlist[0]['name'];?>
				<label class="lblname"><?php echo $l_name;?></label>
				<table border="1" cellspacing="0">
					<tr class="bgtop">
						<th class="date">កាលបរិច្ឆេទ </th>
						<th>ដុល្លា $</th>
						<th>បាត B</th>
						<th>រៀល R</th>
					</tr>
					<?php foreach ( $this->tranlist as $key => $tran) : ?>
						<?php if($tran['name'] != $l_name):?>
							<?php $l_name = $tran['name'];?>
							</table><br/>
							<label class="lblname"><?php echo $l_name;?></label>
							<table border="1" cellspacing="0">
								<tr class="bgtop">
									<th class="date">កាលបរិច្ឆេទ </th>
									<th>ដុល្លា $</th>
									<th>បាត B</th>
									<th>រៀល R</th>
								</tr>
						<?php endif;?>		
							<tr>
								<td class="date"><?php echo date_format(date_create($tran['date']), "d/m/Y H:i:s");;?></td>
								<td><?php echo number_format($tran['dollar'],(!strrpos($tran['dollar'],"."))? 0 : 2);?></td>
								<td><?php echo number_format($tran['bath'],(!strrpos($tran['bath'],"."))? 0 : 2);?></td>
								<td><?php echo number_format($tran['rail'],(!strrpos($tran['rail'],"."))? 0 : 2);?></td>
							</tr>
							
						<?php endforeach; ?>	
				</table>				
			</td>
		</tr>
	</table>
</div>

<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php endif;?>

<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');

	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML = dojo.byId('grid').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();	    
	}	
</script>