<?php
	$this->headTitle('Currency Smart | Transfer page'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<style>
	#grid{
	    margin-top: 10px;		
	}
	.dojoxGridSortNode{
		text-align: center;	
		height: 24px;		
	}
</style>
<?php 
	//User Access level for redirct url
	$url = Application_Form_FrmMessage::getUrl("/kbank/index/edited?tr_id=");
	$url_extend = Application_Form_FrmMessage::getUrl("/kbank/index/extend-date?tr_id=");
?>
<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require("dojox.grid.DataGrid");	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.Dialog");
	var sender_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->sender));?> );
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
            store: sender_store,
            autoComplete: true,                        
            required: true,
            id: "sender",
            name: "sender",
            searchAttr: "name",           
            class: 'fullside', 
            value:'<?php echo $this->sender_id; ?>',          
            missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
            onChange: function() {
            	setValueToOther();
            }
        }, "sender");
		
		//Creat data fror show			
		loadData(<?php print_r($this->tranlist);?>);
		
		dojo.connect(grid, "onRowClick", grid, function(evt){
			var idx = evt.rowIndex,
				item = this.getItem(idx);
			expired=this.store.getValue(item, "is_expired")
			if(expired==1){
				window.location = '<?php echo $url_extend;?>' + this.store.getValue(item, "id");
			}else{
				window.location = '<?php echo $url;?>' + this.store.getValue(item, "id");
			}
			
		});
	});

	function loadData(data){			
		// create an object store
		var objectStore = new dojo.store.Memory({
		       data: data
		 });

		//load data into data grid
		grid = new dojox.grid.DataGrid({
			store: dojo.data.ObjectStore({objectStore: objectStore}),
			autoHeight: true,	
			structure: [
				{ name: "ល.រ", field: "num", width: "50px", cellStyles: "text-align: center;" },
				{ name: "id", field: "id", hidden: true },	
				{ name: "ឈ្មោះអ្នកផ្ញើរ", field: "sender_name", width: "auto" },
				{ name: "លេខទូរស័ព្ទ", field: "tel", width: "auto" },
				{ name: "លេខគណនី", field: "account_no", width: "auto" },
				{ name: "លេខប្រតិបត្តិការ", field: "invoice", width: "auto" },
				{ name: "ចំនួនទឹកប្រាក់", field: "amount", width: "auto" },			
				{ name: "ថ្ងៃផ្ញើរ", field: "start_date", width: "auto" },
				{ name: "ថ្ងៃផុតកំណត់", field: "expired_date", width: "115px", cellStyles: "text-align: right;" },				
				{ name: "រយៈពេលផ្ញើរ", field: "amount_month", width: "95px", cellStyles: "text-align: left;" },
				{ name: "ផុតកំណត់", field: "amount_expired", width: "95px", cellStyles: "text-align: left;color:red" },
				{ name: "ប្រភេទ", field: "is_extend", width: "95px", cellStyles: "text-align: left;color:red" },
				{ name: "is_expired", field: "is_expired", hidden: true },
				
			]
		}, "grid");
		grid.startup();
	}
	
	// Hide the dialog
	function hideDialog() {		
		dijit.byId("viewcounter").hide();		
	}

	//show Dialog
	function showDialog() {		
		//dijit.byId("viewcounter").show();
	}
</script>

<form name="frmlist_mt" action="<?php echo $this->url(array('module'=>'kbank','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<table class="fullside" style=" border-top: 1px solid #000; border-bottom: 1px solid #000; padding: 10px 0 10px 0;">
	<tr>
	    <tr style="height: 60px;">
	    <td width="25%" align="right">
	   		 <input id="sender" >
	     
	    	<!--<select name="status" id="status" class="fullside" dojoType="dijit.form.FilteringSelect" >
				<?php //foreach ($this->statuslist as $key => $rs) : ?>
					<option value="<?php //echo $key;?>" <?php //if($key == $this->status) echo 'selected'?>><?php //echo $rs;?></option>
				<?php //endforeach;?>
	   		</select> -->
	   </td>
	    <td width="25%" align="right">  
	    	<select name="type_money" id="type_money" dojoType="dijit.form.FilteringSelect" 
				style="width: 265px; height: 30px;" >
				<option value="-1" <?php if($this->type_money == -1) echo 'selected="selected"';?> >ជ្រើសរើស ប្រភេទ​លុយ</option> 
				<?php foreach ($this->currencylist as $key => $cur) : ?>
					<option value="<?php echo $cur['id'];?>" <?php if($cur['id'] == $this->type_money) echo 'selected'?>><?php echo $cur['name'];?></option>
				<?php endforeach;?> 
			</select>
	    </td>
	    <td width="25%" align="right">  
	    	ពី៖&nbsp;
			<input type="text" name="from_date" id="from_date" value="<?php echo date_format(date_create($this->from_date), "Y-m-d");?>"
				dojoType="dijit.form.DateTextBox" style="height: 30px; width: 210px;" 
				rangeMessage="កាល​បរិច្ឆេទ  ពី មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ដល់"
				constraints="{datePattern:'dd/MM/yyyy', max:'<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>'}" 
				onchange="dijit.byId('to_date').constraints.min = arguments[0];" />	
	    </td>
	    <td width="25%" align="right">  
	    	ដល់៖&nbsp;
			<input type="text" name="to_date" id="to_date" value="<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>" 
				dojoType="dijit.form.DateTextBox" style=" height: 30px; width: 195px;"
				rangeMessage='កាល​បរិច្ឆេទ  ដល់ មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ពី' 
				constraints="{min:'<?php echo date_format(date_create($this->from_date), "Y-m-d");?>', datePattern:'dd/MM/yyyy'}" 
				onChange="dijit.byId('from_date').constraints.max = arguments[0]; " />	
	    </td>
	</tr>
	<tr>
		<td align="right"><input class="fullside" type="text" name="txt_search" id="txt_search" placeholder="លេខគណនី ឬ លេខទូរស័ព្ទ"  dojoType="dijit.form.TextBox"
			  value='<?php echo $this->txtsearch;?>'/><!-- <input id="sender" > --></td>
		<td align="right"><!-- <input type="text" name="txt_search" id="txt_search" placeholder="លេខគណនី ឬ លេខទូរស័ព្ទ"  dojoType="dijit.form.TextBox"
			 style="width: 265px;  height: 30px;" value='<?php //echo $this->txtsearch;?>'/> -->	</td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="2" >
		</td>
	    <td colspan="2" align="right">  
			 <button dojoType="dijit.form.Button" showLabel="true" type="submit">ស្វែង​រក</button>	
	    </td>
	</tr>
</table>
<table class="fullside">	  	
	  	
	  <tr>
	  	<td colspan="2">&nbsp;</td>
	  </tr>
	  <tr>
	  	<td>	  		
	  		<?php echo $this->result_row;?>
	  	</td>
	  	<td align="right" >
	  		<?php echo $this->rows_per_page;?>
	  	</td>
	  </tr>
	  <tr>
	  	<td colspan="2">
	  		<div id="grid" ></div>
	  	</td>
	  </tr>	
	  <tr>
	  	<td colspan="2" align="center">
	  		<div id="navigetion" style="margin: 0 auto;"><?php echo $this->nevigation;?></div>	  		
	  	</td>
	  </tr>		  
</table>
</form>