<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require('dijit.form.Button');	
</script>
<?php 
$baseurl=$this->baseUrl();
?>
<script type="text/javascript" src="<?php echo $baseurl;?>/js/css3/src.js"></script>
<script type="text/javascript">
	dojo.require('dijit.form.Button');	
</script>
<style>
#loadingOverlay {
    background:  #fff url('//ajax.googleapis.com/ajax/libs/dojo/1.6.2/dijit/themes/claro/images/loadingAnimation.gif') no-repeat 10px 23px;
    padding:30px;
}
</style>
<div id="loadingOverlay">Loading...</div>