<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
	
</script>

<form action="<?php echo $this->url(array('module'=>'agent','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="10" width="100%" >
		<tr>
			<td>
				<fieldset>
					<legend align="right">ដាក់លុយ</legend>
						<table cellspacing="10" cellpadding="0" width="100%" style="font-size: 18px">
						    <tr>
						        <td>លេខគណនី</td>
						        <td><?php echo $form->getElement('nuber_account');?></td>
						        <td></td>
						        <td></td>
						    </tr>
						     <tr>
						        <td>ឈ្មោះអ្នកអតិជន</td>
						        <td><?php echo $form->getElement('namesend');?></td>
						        <td>ថ្ញៃដាក់ប្រាក់</td>
						        <td><?php echo $form->getElement('daydokmoney');?></td>
						    </tr>
						     <tr>
						        <td>លេខទូរស៏ព</td>
						        <td><?php echo $form->getElement('phong');?></td>
						        <td>សំគាល់</td>
						        <td><?php echo $form->getElement('note1');?></td>
						    </tr>
						     <tr>
						        <td>ប្រាក់ជាដុល្លា</td>
						        <td><?php echo $form->getElement('dola');?></td>
						        <td>ដាក់ប្រាក់ជាដុល្លា</td>
						        <td><?php echo $form->getElement('dola1');?></td>
						    </tr>
						    <tr>
						        <td>ប្រាក់ជាបាត</td>
						        <td><?php echo $form->getElement('bath');?></td>
						        <td>ដាក់ប្រាក់ជាបាត</td>
						        <td><?php echo $form->getElement('bath1');?></td>
						    </tr>
						    <tr>
						        <td>ប្រាក់ជារៀល</td>
						        <td><?php echo $form->getElement('real');?></td>
						        <td>ដាក់ប្រាក់ជារៀល</td>
						        <td><?php echo $form->getElement('real1');?></td>
						    </tr>
						</table>
						
				</fieldset>
				
			</td>			
		</tr>
		<table width="100%" style="font-size: 18px">
		                 <tr>
						        ​​​<th>ប្រភេទលុយ</th>
						         <th>ចំនួន</th>
						         <th>ថ្លៃសេវាកម្ម</th>
						         <th>ប្រាក់ទទួល</th>
						         <th>ប្រាក់អាប់</th>
						         <th>សំគាល់</th>
						 </tr>
						 <tr>
						          <td><?php echo $form->getElement('type');?></td>
						          <td><?php echo $form->getElement('number');?></td>
						          <td><?php echo $form->getElement('serv');?></td>
						          <td><?php echo $form->getElement('get');?></td>
						          <td><?php echo $form->getElement('up');?></td>
						          <td><?php echo $form->getElement('_note');?></td>
						 </tr>
						
						</table>
		
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


