<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
        
	$form = $this->frm;
	
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>

<form action="<?php echo $this->url(array('module'=>'partner','controller'=>'index','action'=>'edite')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
	<table cellspacing="1" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend style="font-size: 15px; font-family:'Khmer OS Muol'; color: black;"><strong>ពត័មាន ទំនាក់ទំនង របស់​ភ្នាក់ងារ</strong></legend>
						<table width="100%" style="font-size: 15px; font-family:'Khmer OS Battambang';">
						   
							<tr>
								<td>ដៃគូមេ</td><?php echo $form->getElement('id');?>
								<td><?php echo $form->getElement('main_branch');?></td>
								<td>ឈ្មោះដៃគូរសហការណ៏</td>
								<td><?php echo $form->getElement('branch_name');?></td>
								<td></td>
								<td></td>
							</tr>
							<tr>
								<td>ឈ្មោះអ្នកគ្រប់គ្រង</td>
								<td><?php echo $form->getElement('partner_name');?></td>
								<td>លេខអត្តសញ្ញាណប័ណ្ណ</td>
								<td><?php echo $form->getElement('cade_number');?></td>
								<td>លេខគណនេយ្យ</td>
								<td><?php echo $form->getElement('accournt_number');?></td>
							</tr>
							<tr>
								<td>រូបថត</td>
								<td><?php echo $form->getElement('photo');?></td>
								<td>អាស័យដ្ឋាន</td>
								<td><?php echo $form->getElement('address');?></td>
								<td>លេខផ្ទះ</td>
								<td><?php echo $form->getElement('home_number');?></td>
							</tr>
							<tr>
								<td>លេខក្រុម</td>
								<td><?php echo $form->getElement('group_number');?></td>
								<td>លេខផ្លូវ</td>
								<td><?php echo $form->getElement('street_number');?></td>
								<td>ឃុំ/សង្កាត់</td>
								<td><?php echo $form->getElement('commun_number');?></td>
							</tr>
							<tr>
								<td>ស្រុក/ខ័ណ្ឌ</td>
								<td><?php echo $form->getElement('district_number');?></td>
								<td>ខេត្ត/ក្រុង</td>
								<td><?php echo $form->getElement('province_number');?></td>
				                <td>លេខទូរស័ព្ទ  </td>
								<td><?php echo $form->getElement('fax_number');?></td>
								
							</tr>
							<tr>
								
								<td>លេខទូរស័ព្ទដៃ</td>
								<td><?php echo $form->getElement('sele_phone');?></td>
								<td>កាលបរិច្ឆេត</td>
								<td><?php echo $form->getElement('date');?></td>
								<td>ស្ថានភាព</td>
								<td><?php echo $form->getElement('status');?></td>
							</tr>
							<tr>
								<td>សំគាល់</td>
								<td colspan="5"><?php echo $form->getElement('note');?><br /></td>
								
							</tr>
							
						</table>
								
				</fieldset>
				<fieldset>
					<legend style="font-size: 15px; font-family:'Khmer OS Muol'; color: black;">ពត៏មាន​សាច់ប្រាក់ក្នុងគណនី</legend>
					<table width="100%" style="font-size: 15px; font-family:'Khmer OS Battambang';">
						<tr>
							<td colspan="6"></td>
							
						</tr>
						<tr>
							<td >ប្រាក់ដុល្លា</td>
							<td><?php echo $form->getElement('money_usa');?></td>
							<td>ប្រាក់បាត</td>
							<td><?php echo $form->getElement('money_bath');?></td>
							<td>​ប្រាក់រៀល</td>
							<td><?php echo $form->getElement('money_riel');?></td>
						</tr>
						<tr>
							<td><!-- ទូទាត់សាច់ប្រាក់ជាមួយ --></td>
							<td><?php //echo $form->getElement('status_getmoney');?></td>
							<td>ប្រតិបត្តការណ័</td>
							<td><?php echo $form->getElement('tran_type');?></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td colspan="6"></td>
							
						</tr>
					</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


