<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	
</script>

<form action="<?php echo $this->url(array('module'=>'agent','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="10" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend align="right">ពត័មាន ​ដាក់ប្រាក់</legend>
						<table cellspacing="5" cellpadding="0" width="100%">
						  <tr>
							 <td>លេខគណី</td>
							 <td><?php echo $form->getElement('nuber_account');?></td>
							
							
							 <td>លេខទូរស៏ព្ទ</td>
							 <td><?php echo $form->getElement('phone1');?></td>
						
							
							 <td>ឈ្មោះអ្នកដាក់</td>
							 <td><?php echo $form->getElement('name_input1');?></td>
						</tr>
						<tr>
							 <td>ដាក់ប្រាក់ជាដុល្លា</td>
							 <td><?php echo $form->getElement('dola2');?></td>
							 <td>ដាក់ប្រាក់ជាបាត</td>
							 <td><?php echo $form->getElement('bath2');?></td>
							 <td>ដាក់ប្រាក់ជាបាត</td>
							 <td><?php echo $form->getElement('real');?></td>
						
							
						</tr>
							
							
					</table>
				</fieldset>
			</td>			
		</tr>
	      <table>
	                       <tr>
							  <td>ប្រភេទលុយ</td>
							  <td>ចំនួន</td>
							  <td>ថ្លៃសេវាកម្ម</td>
							  <td>ប្រាក់ទទួល</td>
							  <td>ប្រាក់អាប់</td>
							  <td>សំគាល់</td>
							</tr>
							
	                      <tr>
						   <td><?php echo $form->getElement('typecash');?></td>
							  <td><?php echo $form->getElement('nuber');?></td>
							  <td><?php echo $form->getElement('nuber1');?></td>
							  <td><?php echo $form->getElement('nuber2');?></td>
							  <td><?php echo $form->getElement('nuber3');?></td>
							  <td><?php echo $form->getElement('nuber4');?></td>
							</tr>
	      </table>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


