<?php
	$this->headTitle('Currency Smart | Current Balance page'); 
	echo $this->headTitle();
	$session_user=new Zend_Session_Namespace('auth');
?>	
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.html");
	dojo.require('dijit.form.Select');	
	dojo.require('dojo.domReady!');	
	
	
	
	dojo.ready(function(){		
		
		addAmountTypeMoney();
		var txtcommission = dojo.byId("currency_type1");
		dojo.connect(txtcommission, "onkeyup", function(evt){			
			
	    });	

		
		
	});  
	    
</script>
<style>
<!--
	.tbtable{		
		font-weight: bolder;
		line-height: 40px;
		text-align: center;
	}
	.tbtable .tbheader{
		background-color: #012a15;
		text-align: left;
		color: #fff;
	}
	.tbtable .first{
		background-color: #016315;
		color: #fff;
	}
	.tbtable .first td{
		width: 33.33%
	}
	.tbtable .second{
		background-color: #fff; 
		color: black;
	}
	.nevg-value{
		color: RED;
	}
	.tbtable .second .input-inner {
		margin: 0px;
		padding: 0px;
		width: 99%;	
		border: none;
	}
	
	#dollar.dijitInputInner, #bath.dijitInputInner, #rail.dijitInputInner{
		text-align: center;		
		background-color: #FFFFFF !important;
	}
	
	.bg-white{
		background-color: #FFFFFF !important;		
	}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
}
-->
</style>


<?php if($session_user->level == 1): //Admin View Only?>
<form id='frm_search_capital' action="<?php echo $this->url(array('module'=>'capital','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<select style="text-align: left;" name="user_id" id="select_user_id" dojoType="dijit.form.FilteringSelect" required="true"> 
		<?php foreach ($this->users as $key => $u) : ?>
			<option value="<?php echo $u['id'];?>" <?php echo ($u['id'] == $this->user_id)?"selected":"";?>><?php echo  $u['name'];?></option>
		<?php endforeach;?> 
	</select> 
	<input type="hidden" name="actions" value="search">
</form>
<?php endif;?>

<form id='frm_add_capital' action="<?php echo $this->url(array('module'=>'capital','controller'=>'cash','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('doloar').get('value') == 0 && dijit.byId('bath').get('value') == 0 && dijit.byId('rail').get('value') == 0){
					dijit.byId('doloar').focus();
					return false;
				}

				return true;
			} else {
				return false;
			}
	</script>	 
	
	<table class="tbtable" style="margin:10px auto; width:100%;">
		<tr class="tbheader">
			<td>&nbsp;បន្ថែមសន្លឺកទឹកប្រាក់នៅទីនេះ !</td>
		</tr>
		<tr>
			<td>	
			</td>
		</tr>
		<?php if($session_user->level == 1): //Admin Upadte Only?>
		<tr>
			<td>	
				<table cellspacing='0' border="1" style="width: 100%;">									
					<tr>
						<td>សំរាប់ថ្ងៃ</td>
						<td><input type="text" name="date" id="date" data-dojo-type="dijit.form.DateTextBox"
									data-dojo-props="required:true,																		
									name:'date',
									id:'date',	
									value:'<?php echo date('Y-m-d');?>',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
									<input type="hidden" name="record_row" id="record_row" dojoType="dijit.form.TextBox" />
									</td>
					</tr>									
				</table>	
			</td>
		</tr>
		
		<tr>
			<td>
			 	<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
					<tr id="head_title" class="head-title" align="center"></tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align="left">
				<input id="add-append" value="បញ្ជូលសន្លឹក" label="បញ្ជូលសន្លឹក" dojoType="dijit.form.Button" iconClass="dijitIconApplication" Onclick="addAmountTypeMoney();" />
			</td>
		</tr>
		<tr>
			<td align="right">  
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" />				 
			</td>
		</tr>
		<?php endif;?>
	</table>
	<input type="hidden" name="user_id" value="<?php echo $this->user_id;?>">
	<input type="hidden" name="actions" value="add_capital">
</form>
<script type="text/javascript">
function getSupCurrency(chapter,index){
	/*$('#account_'+index +' option').each(function(i, option){ $(option).remove(); });
	var temp='<option value="">---Account---</option>';
	$('#account_'+index).append(temp);
	var val=$('#chapter_'+index).val();		
	for(var i=0;i<chapter.obj.length;i++){			
		if(chapter.obj[i].account != ''){
			if(chapter.obj[i].account.substr(0,val.length) == val)	
				$('#account_'+index).append('<option value="'+chapter.obj[i].account+'">'+chapter.obj[i].account+'</option>');
		}
	}*/
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_capital"+ids).remove();
		
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_capital"+index).remove();
	}
	
}

	curr_option = '<?php echo $this->curr_type;?>';
	curr_dollar_amountoption = '<?php echo $this->curr_dollaramountoption;?>';
	temp='';
	r = 0;
	fund_title=0;
	function addAmountTypeMoney(){
			/*if(dijit.byId("sender_name").value==0 || dijit.byId("sender_name").value==null || dijit.byId("sender_name").value==false)
			{ alert('សូមជ្រើសរើសឈ្មោះអ្នកជំពាក់');return false;}*/
			r++;
			if(fund_title!=1){
				thead='<th>លរ</th>';
				thead+='<th>លុប</th>';
				thead+='<th>​ប្រភេទប្រាក់</th>';
				thead+='<th>ប្រភេទចំនួន($)សរុប</th>';
				thead+='<th>ចំនួនសន្លឹក</th>';
				thead+='<th>ផ្សេងៗ </th>';
				fund_title=1;
				dojo.query("#head_title").append(thead);
			}
			
		    temp='<td width="6%" align="center">'+r+'</td>';
			temp+='<td><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="/cs01/public/images/actions/Delete_16.png"></td>';
			temp+='<td align="center"><select onchange="setAccount(currency_type,'+r+')" id="currency_type_'+r+'" name="currency_type_'+r+'" dojoType="dijit.form.FilteringSelect"  >'+curr_option+'</select></td>';
			temp+='<td><select id="curr_amountoption_'+r+'" name="curr_amountoption_'+r+'" dojoType="dijit.form.FilteringSelect"  >'+curr_dollar_amountoption+'</select></td>';
			temp+='<td><input type="text" required="true" name="pcs_'+r+'" id="pcs_'+r+'" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" name="note_'+r+'" id="note_'+r+'" dojoType="dijit.form.NumberTextBox" s/></td>';
			tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
			tmp+="</tr>";
				dojo.query("#t_amountmoneytype").append(tmp);
				dojo.html.set(dojo.byId("row_capital"+r),temp, {
			    parseContent: true,
			     
			});
			if(dijit.byId("record_row").value!="") {
				var ids = dijit.byId("record_row").value;
				dijit.byId("record_row").attr('value',ids+','+r);
			} else { dijit.byId("record_row").attr('value',r);}
	}	
</script>