<?php
	$this->headTitle('Currency Smart | Current Balance page'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$session_user=new Zend_Session_Namespace('auth');
	$rs = $this->rs;
	$d = 0;
	$b = 0;
	$r = 0;
	
	$date = $rs['date'];
	$date = date('d/m/Y',strtotime($date));
	$sign=$rs['sign']==1?'':"-";
	$old_amount = $rs['amount'];
	if($rs['curr_type']==1){
		$d = $sign.$rs['amount'];
	}elseif($rs['curr_type']==2){
		$b= $sign.$rs['amount'];
	}elseif($rs['curr_type']==3){
		$r= $sign.$rs['amount'];
	}
?>	
<script>
dojo.ready(function(){
	d = dijit.byId('dollar').get('value');
	if(d==0){
		 dijit.byId('dollar').set('readOnly',true);	
	}
	b = dijit.byId('bath').get('value');
	if(b==0){
		 dijit.byId('bath').set('readOnly',true);	
	}
	r = dijit.byId('rail').get('value');
	if(r==0){
		 dijit.byId('rail').set('readOnly',true);	
	}
	
});
</script>
<style>
<!--
	.tbtable{		
		font-weight: bolder;
		line-height: 40px;
		text-align: center;
	}
	.tbtable .tbheader{
		background-color: #012a15;
		text-align: left;
		color: #fff;
	}
	.tbtable .first{
		background-color: #016315;
		color: #fff;
	}
	.tbtable .first td{
		width: 33.33%
	}
	.tbtable .second{
		background-color: #fff; 
		color: black;
	}
	.nevg-value{
		color: RED;
	}
	.tbtable .second .input-inner {
		margin: 0px;
		padding: 0px;
		width: 99%;	
		border: none;
	}
	
	#dollar.dijitInputInner, #bath.dijitInputInner, #rail.dijitInputInner{
		text-align: center;		
		background-color: #FFFFFF !important;
	}
	
	.bg-white{
		background-color: #FFFFFF !important;		
	}
}
-->
</style>
<form id='frm_add_capital' action="<?php echo $this->url(array('module'=>'capital','controller'=>'index','action'=>'edited')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<select style="text-align: left;" name="user_id" id="user_id" dojoType="dijit.form.FilteringSelect" required="true"> 
		<?php foreach ($this->users as $key => $u) : ?>
			<option value="<?php echo $u['id'];?>" <?php echo ($u['id'] == $rs['user_id'])?"selected":"";?>><?php echo  $u['name'];?></option>
		<?php endforeach;?> 
	</select> 
	<input type="hidden" name="actions" value="search">

<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('doloar').get('value') == 0 && dijit.byId('bath').get('value') == 0 && dijit.byId('rail').get('value') == 0){
					dijit.byId('doloar').focus();
					return false;
				}

				return true;
			} else {
				return false;
			}
	</script>	 
	
	<table class="tbtable" style="margin:10px auto; width:100%;">
		<tr class="tbheader">
			<td>&nbsp;កែប្រែដើមទុន</td>
		</tr>
		<tr>
			<td>	
				<table cellspacing='0' border="1" style="width: 100%;">									
					<tr class="first">
						<td>ដុល្លា $</td>
						<td>បាត B</td>
						<td>រៀល R</td>
					</tr>
					<tr class="second bg-white">
						<td><input type="hidden" name="tran_id" name="tran_id" value='<?php echo $rs['id'];?>' />
							<input type="text" name="dollar" id="dolar"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'dollar',
									id:'dollar',	
									class:'input-inner',								
									value:<?php echo $d;?>,
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
						</td>
						<td>
							<input type="text" name="bath" id="bath"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'bath',
									id:'bath',									
									value:<?php echo $b;?>,
									class:'input-inner',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
						</td>
						<td>
							<input type="text" name="rail" id="rail"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'rail',
									id:'rail',									
									value:<?php echo $r;?>,
									class:'input-inner',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
						</td>
					</tr>	
					<tr>
						<td>សំរាប់ថ្ងៃ</td>
						<td><input type="text" name="date" id="date" data-dojo-type="dijit.form.DateTextBox"
									data-dojo-props="required:true,																		
									name:'date',
									id:'date',	
									value:'<?php echo $rs['date'];?>',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'"></td>
						<td></td>
					</tr>											
				</table>	
			</td>
		</tr>
		<tr>
			<td align="right">  
				<input type="reset" value="សំអាត" label="សំអាត" id="busyButton" dojoType="dijit.form.Button"/>
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" />				 
			</td>
		</tr>
	</table>
	<input type="hidden" name="old_user" value="<?php echo $rs['user_id'];?>" />
	<input type="hidden" name="old_amount" value="<?php echo $old_amount;?>" />
	<input type="hidden" name="old_date" value="<?php echo $date;?>" />
	<input type="hidden" name="actions" value="add_capital" />
	<input type="hidden" name="old_date" value="<?php echo $rs['date'];?>"  />
</form>


<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');	
</script>