<?php
	$this->headTitle('Currency Smart | Capital Page'); 
	echo $this->headTitle();
?>
<style>
	#grid{
	    margin-top: 10px;		
	}
	.dojoxGridSortNode{
		text-align: center;	
	}
</style>
<?php 
	//User Access level for redirct url
	$url = Application_Form_FrmMessage::getUrl("/capital/index/edited?tran_id=");
?>
<script>
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojox.grid.DataGrid");	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.Dialog");
	dojo.require("dojo.number");
	
	dojo.ready(function(){		
		//Creat data fror show			
		loadData(<?php print_r($this->tranlist);?>);
		
		dojo.connect(grid, "onRowClick", grid, function(evt){
			var idx = evt.rowIndex,
				item = this.getItem(idx);
			window.location = '<?php echo $url;?>' + this.store.getValue(item, "id");
		});

		

	});

	function formatDispaly(f){
		return dojo.number.format(f[0]) + " " + f[1];
    }
    
	function loadData(data){			
		// create an object store
		var objectStore = new dojo.store.Memory({
		       data: data
		 });

		//load data into data grid
		grid = new dojox.grid.DataGrid({
			store: dojo.data.ObjectStore({objectStore: objectStore}),
			autoHeight: true,	
			structure: [
				{ name: "ល.រ", field: "num", width: "50px", cellStyles: "text-align: center;" },
				{ name: "id", field: "id", hidden: true },					
				{ name: "ឈ្មោះបុគ្គលិក", field: "agent_name", width: 'auto', cellStyles: "text-align: center;" },
				{ name: "ប្រភេទប្រាក់", field: "curr_type",  width: 'auto', cellStyles: "text-align: center;"},
				{ name: "ចំនួនទឹកប្រាក់", field: "amount",  width: 'auto',cellStyles: "text-align: right;"},
				{ name: "កាលបរិឆ្ឆេទ",field: "date", width: "auto", cellStyles: "text-align: right;"},
			]
		}, "grid");
		grid.startup();
	}
	
</script>

<form name="frmlist_mt" action="<?php echo $this->url(array('module'=>'capital','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<table class="fullside">	  
	  <tr>
		  <td>
		  	<select style="text-align: left;" onchange="dijit.byId('frm_search_capital').submit();" name="staff_name" id="staff_name" dojoType="dijit.form.FilteringSelect" required="true"> 
			<?php foreach ($this->users as $key => $u) : ?>
				<option value="<?php echo $u['id'];?>" <?php echo ($u['id'] == $this->staff_name)?"selected":"";?>><?php echo  $u['name'];?></option>
				<?php endforeach;?> 
			</select> 
		  </td>
		  <td>
		  	<select name="type_money" id="type_money" dojoType="dijit.form.FilteringSelect" 
				style="width: 265px; height: 30px;" >
				<option value="-1" <?php if($this->type_money == -1) echo 'selected="selected"';?> >ជ្រើសរើស ប្រភេទ​លុយ</option> 
				<?php foreach ($this->currencylist as $key => $cur) : ?>
					<option value="<?php echo $cur['id'];?>" <?php if($cur['id'] == $this->type_money) echo 'selected'?>><?php echo $cur['name'];?></option>
				<?php endforeach;?> 
			</select>	
		  </td>
	    <td align="right" colspan="2">	    	
			ពី៖&nbsp;
			<input type="text" name="from_date" id="from_date" value="<?php echo date_format(date_create($this->from_date), "Y-m-d");?>"
				dojoType="dijit.form.DateTextBox" style="height: 30px; width: 210px;" 
				rangeMessage="កាល​បរិច្ឆេទ  ពី មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ដល់"
				constraints="{datePattern:'dd/MM/yyyy', max:'<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>'}" 
				onchange="dijit.byId('to_date').constraints.min = arguments[0];" />
			ដល់៖&nbsp;
			<input type="text" name="to_date" id="to_date" value="<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>" 
				dojoType="dijit.form.DateTextBox" style=" height: 30px; width: 195px;"
				rangeMessage='កាល​បរិច្ឆេទ  ដល់ មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ពី' 
				constraints="{min:'<?php echo date_format(date_create($this->from_date), "Y-m-d");?>', datePattern:'dd/MM/yyyy'}" 
				onChange="dijit.byId('from_date').constraints.max = arguments[0];" />
				<br />
				<button dojoType="dijit.form.Button" showLabel="true" type="submit">ស្វែង​រក</button>	
		</td>
	  </tr>	
	  
	  <tr>
	  	<td colspan="4">&nbsp;</td>
	  </tr>
	  <tr>
	  	<td>	  		
	  		<?php echo $this->result_row;?>
	  	</td>
	  	<td align="right" colspan="3" >
	  		<?php echo $this->rows_per_page;?>
	  	</td>
	  </tr>
	  <tr>
	  	<td colspan="4">
	  		<div id="grid" ></div>
	  	</td>
	  </tr>	
	  <tr>
	  	<td colspan="4" align="center">
	  		<div id="navigetion" style="margin: 0 auto;"><?php echo $this->nevigation;?></div>	  		
	  	</td>
	  </tr>		  
</table>
</form>