<?php 
    $this->headTitle('Currency Smart | Add Money Stock'); 
	echo $this->headTitle();
	$session_user=new Zend_Session_Namespace('auth');
	$form = $this->frm;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'Keeping','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   <td><?php echo $form->getElement("adv_search");?></td>
		   <td><?php echo $form->getElement('send_name');?></td>
		   <td><?php echo $form->getElement('start_date')?></td>
		   <td><?php echo $form->getElement('end_date')?></td>
		   <td><?php echo $form->getElement('status_search');?></td>
		   <td><?php echo $form->getElement('btn_search');?></td>
		   
		</tr>
	</table>
  
</form>
 <?php echo $this->list;?>