<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
  
	$form = $this->frm;
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
dojo.require("dijit.form.SimpleTextarea");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.RadioButton");
dojo.ready(function(){
	var district_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->district));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: district_data}),
	autoComplete: true,
	query: {
		//pro_id: "-1"
		pro_id:"<?php echo $this->row['province'];?>"
	},            
	required: false,		           
	name: "district",
	id: "district",
	searchAttr: "name",
	value: "<?php echo $this->row['district'];?>",
//	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
				filterCommune();
	    }
	}, "district");

	var commune_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->commune_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: commune_data}),
	autoComplete: true,
	query: {
		//district_id: "-1"
		district_id: "<?php echo $this->row['district'];?>"
	},            
	required: false,		           
	name: "commune",
	id: "commune",
	searchAttr: "name",
	value: "<?php echo $this->row['commune'];?>",
	//class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			filterVillage();
  }
	}, "commune");

	var village_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->village_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: village_data}),
	autoComplete: true,
	query: {
		//commune_id:"-1"
		commune_id:"<?php echo $this->row['commune'];?>"
	},            
	required: false,		           
	name: "village",
	id: "village",
	searchAttr: "name",
	//class: 'fullside',
	value: "<?php echo $this->row['village'];?>",
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
}
	}, "village");

	

	
});
function filterDistrict(){
	dijit.byId('district').query.pro_id = dijit.byId('province_name').get('value');
}
function filterCommune(){
	dijit.byId('commune').query.district_id = dijit.byId('district').get('value');
}
function filterVillage(){
	dijit.byId('village').query.commune_id = dijit.byId('commune').get('value');
}

</script>

<form action="<?php echo $this->url(array('module'=>'Keeping','controller'=>'Customer','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" >
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
	<table cellspacing="1" width="100%" style="font-family:'Kh Battambang'">
		<tr>
			<td>
				<fieldset>
					<legend style="font-size: 15px; font-family:'Khmer OS Muol'; color: black;"><strong>ពត័មាន ទំនាក់ទំនង របស់​ភ្នាក់ងារ</strong></legend>
						<table width="100%" style="font-size: 15px; font-family:'Khmer OS Battambang';">
							<tr>
								<td>ដៃគូមេ</td>
								<td><?php echo $form->getElement('main_branch');echo $form->getElement('id')?></td>
								<td>ឈ្មោះដៃគូរសហការណ៏</td>
								<td><?php //echo $form->getElement('branch_name');?>
									<?php echo $form->getElement('branch_name');?>
								</td>
								<td></td>
								<td></td>
							</tr>
							<tr>
								<td>ឈ្មោះអ្នកគ្រប់គ្រង</td>
								<td><?php echo $form->getElement('partner_name');?></td>
								<td>លេខអត្តសញ្ញាណប័ណ្ណ</td>
								<td><?php echo $form->getElement('cade_number');?></td>
								<td>លេខគណនេយ្យ</td>
								<td><?php echo $form->getElement('account_number');?></td>
							</tr>
							<tr>
								<td>ខេត្ត/ក្រុង</td>
								<td><?php echo $form->getElement('province_name');?></td>
								<td>ស្រុក/ខ័ណ្ឌ</td>
								<td><input id="district" ><?php //echo $form->getElement('district_name');?></td>								
				                <td>ឃុំ/សង្កាត់</td>
								<td><input id="commune" ><?php //echo $form->getElement('commune_name');?>
									
								</td>								
							</tr>
							<tr>								
								<td>ភូមិ</td>
								<td><input id="village" ><?php // echo $form->getElement('address');?></td>
								<td>លេខផ្ទះ</td>
								<td><?php echo $form->getElement('home_number');?></td>
								<td>លេខផ្លូវ</td>
								<td><?php echo $form->getElement('street_number');?></td>
							</tr>
							<tr>
								<td>លេខក្រុម</td>
								<td><?php echo $form->getElement('group_number');?></td>								
				                <td>លេខទូរស័ព្ទ  ១ </td>
								<td><?php echo $form->getElement('fax_number');?></td>
								<td>លេខទូរស័ព្ទដៃ​​ ២</td>
								<td><?php echo $form->getElement('sele_phone');?></td>
								
							</tr>
							<tr>
								<td>កាលបរិច្ឆេត</td>
								<td><?php echo $form->getElement('date');?></td>
								<td>ស្ថានភាព</td>
								<td><?php echo $form->getElement('status');?></td>
								<td>សំគាល់</td>
								<td ><?php echo $form->getElement('note');?><br /></td>
							</tr>
							<tr>
								<td>រូបថត</td>
								<td><?php echo $form->getElement('photo');?> <br/>
								<img height="100px" width="100px" src="<?php echo $this->baseUrl().'/images/'.$this->photo;?>" /> 
								</td>
								<td></td>
								<td><?php //echo $form->getElement('status');?></td>
								<td></td>
								<td ><?php //e/cho $form->getElement('note');?><br /></td>
							</tr>
							
						</table>
								
				</fieldset>
				<fieldset>
					<legend style="font-size: 15px; font-family:'Khmer OS Muol'; color: black;">ពត៏មាន​សាច់ប្រាក់ក្នុងគណនី</legend>
					<table width="100%" style="font-size: 15px; font-family:'Khmer OS Battambang';">
						<tr>
							<td colspan="6"></td>
							
						</tr>
						<tr>
							<td >ប្រាក់ដុល្លា</td>
							<td><?php echo $form->getElement('money_usa');?></td>
							<td>ប្រាក់បាត</td>
							<td><?php echo $form->getElement('money_bath');?></td>
							<td>​ប្រាក់រៀល</td>
							<td><?php echo $form->getElement('money_riel');?></td>
						</tr>
						<tr>
							<td><!-- ទូទាត់សាច់ប្រាក់ជាមួយ --></td>
							<td><?php //echo $form->getElement('status_getmoney');?></td>
							<td>ប្រតិបត្តការណ័</td>
							<td><?php echo $form->getElement('tran_type');?></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td colspan="6"></td>
							
						</tr>
					</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក & ចាកចេញ" name="btn_save_close" label="រក្សាទុក & ចាកចេញ" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
				<?php $url_close = $this->url(array('module'=>'Keeping','controller'=>'Customer','action'=>'')); ?>
				<a href="<?php echo $url_close ?>">
				<input type="button" value="ចាកចេញ" name="btn_close" label="ចាកចេញ" id="submitButton_Close" dojoType="dijit.form.Button"  iconClass=" dijitIconDelete"/>							
				</a>
			</td>
		</tr>
	</table>		
</form>