<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("partner"));
$frm = $this->frm_partner;
$form=$this->frm_deposite;
//echo $form;exit();
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'partner','controller'=>'deposite','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   <td><?php echo $frm->getElement("adv_search");?></td>
		   <td><?php  echo $form->getElement('name_partner');?></td>
		   <td><?php echo $frm->getElement('start_date');?></td>
		   <td><?php echo $frm->getElement('end_date');?></td>
		   <td><?php echo $frm->getElement('status_search');?></td>
		   <td><?php echo $frm->getElement("btn_search");?></td>
		   <?php echo $this->list;?>
	   </tr>
   </table>
</form>
<?php 
   echo $this->list;
?>
