
<input type="button" label="Loan Collection" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		   ('module'=>'reports','controller'=>'Index','action'=>'rpttobranch')); ?>';"/>
  
<input type="button" label="rpt-allsummary" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpt-allsummary')); ?>';"/>
  		
<input type="button" label="rpt-debt" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpt-debt')); ?>';"/>
  		
<input type="button" label="rpt-debtloan" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpt-debtloan')); ?>';"/>
  		
<input type="button" label="rpt-deposit" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpt-deposit')); ?>';"/>
  		
<input type="button" label="rpt-fundtran" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpt-fundtran')); ?>';"/>
  		
<input type="button" label="rpt-pcs" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpt-pcs')); ?>';"/>
  		
<input type="button" label="rpt-tran-detail" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpt-tran-detail')); ?>';"/>
  		
<input type="button" label="rpt-withdraw" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpt-withdraw')); ?>';"/>
  		
<input type="button" label="rptautoprint" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptautoprint')); ?>';"/>
  		
<input type="button" label="rptbalance-agent" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptbalance-agent')); ?>';"/>
  		
<input type="button" label="rptbalance" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptbalance')); ?>';"/>
  		
<input type="button" label="rptfund" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptfund')); ?>';"/>
  		
<input type="button" label="rptincome" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptincome')); ?>';"/>
  		
<input type="button" label="rptowe" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptowe')); ?>';"/>
  		
<input type="button" label="rptowes" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptowes')); ?>';"/>
  		
<input type="button" label="rptsummary-exchange" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptsummary-exchange')); ?>';"/>
  		
<input type="button" label="rptsummary-transfer-alluser" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptsummary-transfer-alluser')); ?>';"/>
  		
<input type="button" label="rptsummary-transfer" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rptsummary-transfer')); ?>';"/>
  		
<input type="button" label="rpttobranch" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpttobranch')); ?>';"/>
  		
<input type="button" label="rpttotal" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpttotal')); ?>';"/>
  		
<input type="button" label="rpttotalonly" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array 
  		('module'=>'reports','controller'=>'Index','action'=>'rpttotalonly')); ?>';"/>
  		
  		
  		

  
