<?php
	$this->headTitle('Currency Smart | Capital Page'); 
	echo $this->headTitle();
?>
<style>
	#grid{
	    margin-top: 10px;		
	}
	.dojoxGridSortNode{
		text-align: center;	
	}
</style>
<?php 
	//User Access level for redirct url
	$url = Application_Form_FrmMessage::getUrl("/capital/index/edited?tran_id=");
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
</script>
<script>
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojox.grid.DataGrid");	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.Dialog");
	dojo.require("dojo.number");

	var baseurl = '<?php echo $this->baseUrl();?>';
</script>
<form name="frmlist_mt" action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rpt-pcs')); ?>" dojoType="dijit.form.Form" method="post">
<table class="fullside">	  
	  <tr>
		  <td>
		  <select style="text-align: left;" onchange="dijit.byId('frm_search_capital').submit();" name="staff_name" id="staff_name" dojoType="dijit.form.FilteringSelect" required="true"> 
			<?php foreach ($this->users as $key => $u) : ?>
				<option value="<?php echo $u['id'];?>" <?php echo ($u['id'] == $this->staff_name)?"selected":"";?>><?php echo  $u['name'];?></option>
				<?php endforeach;?> 
			</select> 
		  </td>
		  <td>
		  	<select name="type_money" id="type_money" dojoType="dijit.form.FilteringSelect" 
				style="width: 265px; height: 30px;" >
				<option value="-1" <?php if($this->type_money == -1) echo 'selected="selected"';?> >ជ្រើសរើស ប្រភេទ​លុយ</option> 
				<?php foreach ($this->currencylist as $key => $cur) : ?>
					<option value="<?php echo $cur['id'];?>" <?php if($cur['id'] == $this->type_money) echo 'selected'?>><?php echo $cur['name'];?></option>
				<?php endforeach;?> 
			</select>	
		  </td>
	    <td align="right" colspan="2">	    	
			ពី៖&nbsp;
			<input type="text" name="from_date" id="from_date" value="<?php echo date_format(date_create($this->from_date), "Y-m-d");?>"
				dojoType="dijit.form.DateTextBox" style="height: 30px; width: 210px;" 
				rangeMessage="កាល​បរិច្ឆេទ  ពី មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ដល់"
				constraints="{datePattern:'dd/MM/yyyy', max:'<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>'}" 
				onchange="dijit.byId('to_date').constraints.min = arguments[0];" />
			ដល់៖&nbsp;
			<input type="text" name="to_date" id="to_date" value="<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>" 
				dojoType="dijit.form.DateTextBox" style=" height: 30px; width: 195px;"
				rangeMessage='កាល​បរិច្ឆេទ  ដល់ មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ពី' 
				constraints="{min:'<?php echo date_format(date_create($this->from_date), "Y-m-d");?>', datePattern:'dd/MM/yyyy'}" 
				onChange="dijit.byId('from_date').constraints.max = arguments[0];" />
				<br />
				<button dojoType="dijit.form.Button" showLabel="true" type="submit">ស្វែង​រក</button>	
		</td>
	  </tr>	
</table>
</form>
		<style>
				.fontbig{
					font-size: 12px;	
				}
				.fonttel{
					font-size: 11px;	
				}
				.pleft{
					width: 110px;	
				}
				tr{ height: 22px;}
	     </style>	
	     <button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
<div id="divPrint"​ padding: 0px; margin: 0px;">	
		<table style="width:100%; font-size: 10pt; padding: 0px; margin: 0px; line-height: 17px;">
				   <tr>
					   	<td align="center" colspan="3">	
			            </td>	   	        
				   </tr> 
				   <tr>
						<td align="center" colspan="3" style="font-family:'KH Koulen'; font-size:14px;" colspan="4">ប័ណ្ណរាប់ក្រដាសប្រាក់</td>
				   </tr>
				   <tr>
				   	   <td colspan="3">
				   	   
				   	   </td>
				   </tr>
				   <tr>
				   		<td colspan="3">
				   <?php 
				     if(!empty($this->rpt_list['err'])){
				     	echo "<script> alert('មិន​ទាន់​មាន​ទន្និន័យ​នូវ​ឡើយ​ទេ!');";
				     		
				     	echo"</script>";
				    echo"</td></tr>";
				     }else{
				   $staff_name = ''; $curr_type = '';
				   		$total_dollar = 0;$total_bath=0; $total_riel=0;
				   ?>
				   <?php foreach($this->rpt_list as $key=>$rs){?>
				   <?php  if ($staff_name!=$rs['staff_name']){?>
				   <?php if($key>0){?>
				   		      </table>
					    	</td>
					   </tr>
					   <tr>
						<td colspan="3" align="right">
							<table width="30%" style="border:1px solid #000; border-collapse: collapse; font-weight:bold;" cellpadding="5" cellspacing="5" border="1" >
								<tr>
									<td colspan="2" align="center" style="background:#ccc;">&nbsp;សរុបរួម&nbsp;</td>
								</tr>
								<tr>
									<td>&nbsp;ប្រភេទប្រាក់&nbsp;</td>
									<td>&nbsp;សរុប&nbsp;</td>
								</tr>
								<tr>
									<td>&nbsp;ដុល្លា $&nbsp;</td>
									<td>&nbsp;<?php echo number_format($total_dollar);?>&nbsp;$</td>
								</tr>
								<tr>
									<td>&nbsp;បាត B&nbsp;</td>
									<td>&nbsp;<?php echo number_format($total_bath);?>&nbsp;B</td>
								</tr>
								<tr>
									<td>&nbsp;រៀល ៛&nbsp;</td>
									<td>&nbsp;<?php echo number_format($total_riel);?>&nbsp;៛</td>
								</tr>
							</table>
						</td>			
				      </tr>
				   <?php $total_dollar = 0;$total_bath=0; $total_riel=0; 
				   }
				   }
				   $rs['volum'] = Application_Model_DbTable_DbGlobal::CurrencyOption($rs['currency_type'],$rs['volum']);
				   if($rs['currency_type']==1){
				   		$total_dollar = $total_dollar+($rs['volum']*$rs['psc_amount']);
				   		
				   }elseif($rs['currency_type']==2){
				   		$total_bath=$total_bath+($rs['volum']*$rs['psc_amount']);
				   }elseif($rs['currency_type']==3){
				   		$total_riel = $total_riel+($rs['volum']*$rs['psc_amount']);
				   }
				   ?>
				   <?php  if ($staff_name !== $rs['staff_name']){?>
				   	 <tr>
					   	<td width="30%">ឈ្មោះបុគ្គលិក៖​  <?php echo $rs['staff_name'];?> </td>	   	        
						<td align="right" colspan="2"></td>
				 	  </tr>
				   <?php } ?>
				  <?php  if ($staff_name !== $rs['staff_name']){?>
				    <tr style=" border:1px solid #000;">
				    	<td colspan="3">
				    		<table border="1" style="border:1px solid #000;border-collapse: collapse;" cellpadding="3" width="100%">
					    		<tr style="background:#7A7C83; height: 25px;">
<!-- 					    		    <th width="25%">ប្រភេទលុយ</th> -->
							   		<th width="25%">ប្រភេទសន្លឹក</th>
							   		<th width="25%">ចំនួនសន្លឹក</th>
						   		    <th>សរុប</th>
						   		</tr>
					 <?php }
					  if ($curr_type!=$this->curr_type[$rs['currency_type']] OR $staff_name !== $rs['staff_name'] ){?>
					  		<tr bgcolor="#ccc">
					  			<td colspan="3">ប្រភេទប្រាក់ (<?php echo $this->curr_type[$rs['currency_type']];?> )</td>
					  		</tr>	
				    <?php   }
					 
					 $staff_name = $rs['staff_name']; $curr_type=$this->curr_type[$rs['currency_type']]?>
						   		 <?php //foreach($this->rpt_list as $key=>$rs){?>
								 <tr>
								 <!--  <td>&nbsp;<?php //echo $rs['currency_type']?>&nbsp;</td> -->
								   	<td>&nbsp;<?php echo number_format($rs['volum'],0).$this->curr_type[$rs['currency_type']];?>&nbsp;</td>
								   	<td>&nbsp;<?php echo $rs['psc_amount'];?> សន្លឹក&nbsp;</td>
								   	<td>&nbsp;<?php echo  number_format($rs['volum']*$rs['psc_amount'])." ".$this->curr_type[$rs['currency_type']];?>&nbsp;</td>
								 </tr>
								<?php //}?>
				    		<!-- </table>
				    	</td>
				   </tr>-->
				   <?php } 
				     } ?>
				   <?php if(empty($this->rpt_list['err'])){?>
				         </table>
				    	</td>
				   </tr>
				   <tr>
						<td colspan="3" align="right">
							<table width="30%" style="border:1px solid #000; border-collapse: collapse; font-weight:bold;" cellpadding="5" cellspacing="5" border="1" >
								<tr>
									<td colspan="2" align="center" style="background:#ccc;">&nbsp;សរុបរួម&nbsp;</td>
								</tr>
								<tr>
									<td>&nbsp;ប្រភេទប្រាក់&nbsp;</td>
									<td>&nbsp;សរុប&nbsp;</td>
								</tr>
								<tr>
									<td>&nbsp;ដុល្លា $&nbsp;</td>
									<td>&nbsp;<?php echo number_format($total_dollar);?>&nbsp;$</td>
								</tr>
								<tr>
									<td>&nbsp;បាត B&nbsp;</td>
									<td>&nbsp;<?php echo number_format($total_bath);?>&nbsp;B</td>
								</tr>
								<tr>
									<td>&nbsp;រៀល ៛&nbsp;</td>
									<td>&nbsp;<?php echo number_format($total_riel);?>&nbsp;៛</td>
								</tr>
							</table>
						</td>			
				    </tr>
				     <?php }?>
			</table>
</div>
	<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		
