<?php
	$this->headTitle('Currency Smart | Report Fund'); 
	echo $this->headTitle();
?>	
<style>
.style-bold{font-weight: bold;}
</style>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.form.DateTextBox");

	 var sender_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->senderlist));?> );  
	
	function doPrint(div_id) {
		window.frames["print_frame"].document.body.innerHTML = dojo.byId('grid_'+ div_id).innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    confirmSubmit(div_id);	
	    	    
	}
	function confirmSubmit(div_id){
		/*if (confirm("តើ​អ្នកជំពាក់នេះពិតជាបានសងរួចហើយរឺទេ ?")){
			dijit.byId('frmlist_fn_rpt_'+ div_id).submit();			
		}*/
	}
</script>
<script type="text/javascript">
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
            store: sender_store,
            autoComplete: true,                        
            required: true,
            id: "sender_name",
            name: "sender_name",
            searchAttr: "name",
            value: "<?php echo $this->selected;?>",     
            class: 'fullside',            
            missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
            onChange: function() {                
            }
        }, "sender_name");
	}); 

</script>


<form name="frmlist_fund" action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rptfund')); ?>" dojoType="dijit.form.Form" method="post">
	<table width="100%" style=" border-top: 1px solid #000; border-bottom: 1px solid #000; padding: 10px 0 10px 0;">
		<tr>
		    <td width="25%">  	
				<input id="sender_name" />	
		    </td>
		    <td width="35%">  	
		    </td>
		    <td width="20%" align="right"> 
		    	ពី៖&nbsp;
				<input type="text" name="from_date" id="from_date" value="<?php echo date_format(date_create($this->from_date), "Y-m-d");?>"
					dojoType="dijit.form.DateTextBox" style="height: 30px; width: 210px;" 
					rangeMessage="កាល​បរិច្ឆេទ  ពី មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ដល់"
					constraints="{datePattern:'dd/MM/yyyy', max:'<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>'}" 
					onchange="dijit.byId('to_date').constraints.min = arguments[0]; " /> 	
		    </td>
		    <td width="20%" align="right"> 
		    	ដល់៖&nbsp;
				<input type="text" name="to_date" id="to_date" value="<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>" 
				dojoType="dijit.form.DateTextBox" style=" height: 30px; width: 195px;"
				rangeMessage='កាល​បរិច្ឆេទ  ដល់ មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ពី' 
				constraints="{min:'<?php echo date_format(date_create($this->from_date), "Y-m-d");?>', datePattern:'dd/MM/yyyy'}" 
				onChange="dijit.byId('from_date').constraints.max = arguments[0]; " /> 	
		    </td>
		</tr><tr style="height: 60px;">
		    <td colspan="4" align="right"> 
		    <input type="submit" value="ស្វែង​រក" label="ស្វែង​រក" id="submitButton" 
						dojoType="dijit.form.Button"  iconClass="dijitIconSearch"/> 	
		    </td>
		</tr>
	</table>
</form>
<br/>

<?php if(!empty($this->fundlist['err']) && $this->fundlist['err']):?>
	<script type="text/javascript">
		alert("<?php echo $this->fundlist['msg']?>");
	</script>
	<table style="width: 100%; line-height: 25px;">		
		<tr>
			<td colspan="2" style="color: red; text-align: center;">
				<br/><br/>
				<?php echo $this->fundlist['msg']?>
			</td>
		</tr>
	</table>
	<br/><br/><br/>
<?php else:?>
<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
	showLabel="false" type="button" onclick="doPrint('1');">Print</button><br/>
<div id="grid_1" >
	<form name="frmlist_fn_rpt_1" id="frmlist_fn_rpt_1" dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'updateowe')); ?>"  method="post">
		<table style="width: 100%; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
			<?php $num=1; $l_ower = ''; $pa = '5px'; $row_id=1; $div_id=2; 
			$_riel_before=0; $_reil_fund=0; $_bath_before=0;
			$_bath_fund=0; $_dollar_before=0;$_dollar_fund=0;$all_r =array(0,0,0,0,0,0);
			?>	
			<?php if(!empty($this->fundlist))  foreach ( $this->fundlist as $key => $tran) { ?>
			
			<?php $ower = ($tran['sender_name']!="" ? $tran['sender_name'] : "Unknow");//not used if ($l_ower !== $ower){?>					
				<?php  if ($l_ower !== $ower){?>
				<?php if($key > 0) {
					
				?>	
					</table><br />
					<table style="width: auto; min-width:50%; float:right; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
						 <tr class="bgtop style-bold">
							  	<td align="right" colspan="2" style="border:1px solid #000;"><b style="font-size: 17px;">&nbsp;ប្រភេទ ​ &nbsp;</b></td>
							  	<td align="center" style="border:1px solid #000;"><b style="font-size: 17px;">&nbsp;ប្រាក់ជំពាក់សរុប ​ &nbsp;</b></td>
							  	<td align="center" style="border:1px solid #000;"><b style="font-size: 17px;">&nbsp;ប្រាក់សងសរុប&nbsp;</b></td>
							  	<td align="center" style="border:1px solid #000;"><b style="font-size: 17px;">&nbsp;ប្រាក់នៅសល់សរុប&nbsp;</b></td>
						 </tr> 
						  <tr>
							  	<td align="right" colspan="2" style="border:1px solid #000;"><b style="font-size: 17px;">$ ​&nbsp;</b></td>
							  	<td align="center" style="border:1px solid #000;"><b><?php echo $_dollar_before; ?></b></td>
							  	<td align="center" style="border:1px solid #000;"><b><?php echo $_dollar_fund; ?></b></td>
							  	<td align="center" style="border:1px solid #000;"><b><?php echo $_dollar_before-$_dollar_fund; ?></b></td>
						 </tr>
						  <tr>
							  	<td align="right" colspan="2" style="border:1px solid #000;"><b style="font-size: 17px;">B​ &nbsp;</b></td>
							  	<td align="center" style="border:1px solid #000;"><b><?php echo $_bath_before;?></b></td>
							  	<td align="center" style="border:1px solid #000;"><b><?php echo $_bath_fund;?></b></td>
							  	<td align="center" style="border:1px solid #000;"><b><?php echo $_bath_before-$_bath_fund;?></b></td>
						 </tr> 
						  <tr>
							  	<td align="right" colspan="2" style="border:1px solid #000;"><b style="font-size: 17px;">R &nbsp;</b></td>
							  	<td align="center" style="border:1px solid #000;"><?php echo $_riel_before; ?></td>
							  	<td align="center" style="border:1px solid #000;"><?php echo $_reil_fund; ?></td>
							  	<td align="center" style="border:1px solid #000;"><?php echo $_riel_before-$_reil_fund;; ?></td>
						 </tr>  
				 </table>
					<br /><br /><br /><br /><br />
					<table style="width: 100%; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
	</form>
</div>
				<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
					showLabel="false" type="button" onclick="doPrint('<?php echo $div_id;?>');">Print</button><br/>
				<div id="grid_<?php echo $div_id;?>" >					
   <form name="frmlist_fn_rpt_<?php echo $div_id;?>" id="frmlist_fn_rpt_<?php echo $div_id;?>" dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rptfund')); ?>"  method="post">
				<?php $div_id++;?>
				<?php }  
				}//end if do print?>
			<?php  if ($l_ower !== $ower){?>
			<?php //$l_ower = $ower; $row_id=1; 
			?>
			<tr class="bgtop" height="40px">
				<td colspan="7" style="border:1px solid #000;">&nbsp;ឈ្មោះ <strong><?php echo $ower; ?></strong></td>
			</tr>
			<tr class="bgtop" align="center">
				<td><b style="font-size: 17px;">&nbsp;ល.រ&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;លេខប្រតិបត្តិការណ៏&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;ថ្ងែខែសង&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;ដុល្លា&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;បាត&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;រៀល&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;ផ្សេងៗ&nbsp;</b></td>
			</tr>
			
			<?php 
				$db_tran = new Application_Model_DbTable_DbFund();
				$_dollar_before=$db_tran->getTotalmoneyOwe($ower,1,$this->from_date,$this->to_date);
				$_bath_before=$db_tran->getTotalmoneyOwe($ower,2,$this->from_date,$this->to_date);
				$_riel_before=$db_tran->getTotalmoneyOwe($ower,3,$this->from_date,$this->to_date);
			
			?>
				
			<?php $l_ower = $ower; $row_id=1;?>
			
		<?php };//endif of->($l_ower != $tran['agentname'].$sub_agent)//good?>
		<?php 
				$_reil_fund= $_reil_fund+(empty($tran['refund_riel'])? 0 : $tran['refund_riel'] );//true
				$_bath_fund = $_bath_fund+(empty($tran['refund_bath'])? 0 : $tran['refund_bath']);//true
				$_dollar_fund = $_dollar_fund +(empty($tran['refund_dollar'])? 0 : $tran['refund_dollar'] );//true
		
		?>
			 <tr>
						<td class="td_line" style="padding-left: <?php echo $pa;?>; border:1px solid #000;"><?php echo $num;$num++;?></td>
						<td class="td_line" style="padding-left: <?php echo $pa;?>; border:1px solid #000"><?php echo $tran["invoice_found"];?>&nbsp;</td>
						<td class="td_line" style="padding-left: <?php echo $pa;?>; border:1px solid #000"><?php echo $tran["date_refund"];?>&nbsp;</td>
						<td align="center" class="td_line" style="border:1px solid #000;"><strong><?php if(!empty($tran['refund_dollar'])) echo number_format($tran['refund_dollar'],(!strrpos($tran['refund_dollar'],"."))? 0 : 2); ?></strong></td>
						<td align="center" class="td_line" style="border:1px solid #000;"><?php if(!empty($tran['refund_bath'])) echo number_format($tran['refund_bath'],(!strrpos($tran['refund_bath'],"."))? 0 : 2); ?></td>
						<td align="center" class="td_line" style="border:1px solid #000;"><strong><?php if(!empty($tran['refund_riel'])) echo number_format($tran['refund_riel'],(!strrpos($tran['refund_riel'],"."))? 0 : 2);?></strong></td>
						
						<td align="center" class="td_line" style="border:1px solid #000;"></td>
			  </tr>
			  
			 
		<?php }//end forearch ?>
		</table><br />
		<table style="width: auto; min-width:50%; float:right; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
	 				<tr class="bgtop style-bold">
						  	<td align="right" colspan="2" style="border:1px solid #000;"><b style="font-size: 17px;">&nbsp;ប្រភេទ ​ &nbsp;</b></td>
						  	<td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់ជំពាក់សរុប&nbsp;</td>
						  	<td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់សងសរុប&nbsp;</td>
						  	<td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់នៅសល់សរុប&nbsp;</td>
					 </tr> 
					  <tr>
						  	<td align="right" colspan="2" style="border:1px solid #000;"><b style="font-size: 17px;">$ ​&nbsp;</b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_dollar_before; ?></b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_dollar_fund; ?></b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_dollar_before-$_dollar_fund; ?></b></td>
					 </tr>
					  <tr>
						  	<td align="right" colspan="2" style="border:1px solid #000;"><b style="font-size: 17px;">B​ &nbsp;</b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_bath_before ?></b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_bath_fund; ?></b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_bath_before-$_bath_fund; ?></b></td>
					 </tr> 
					  <tr>
						  	<td align="right" colspan="2" style="border:1px solid #000;"><b style="font-size: 17px;">R &nbsp;</b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_riel_before; ?></b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_reil_fund; ?></b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_riel_before-$_reil_fund; ?></b></td>
					 </tr>  
		</table><br/><br/>
	</form>
</div>

<iframe marginwidth="45" marginheight="45" name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php endif;?>