<?php
	$this->headTitle('Currency Smart | Report Owes'); 
	echo $this->headTitle();
?>	
<style>
.style-bold{font-weight: bold;}
</style>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.form.DateTextBox");

	 var sender_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->senderlist));?> );  
	
	function doPrint(div_id) {
		window.frames["print_frame"].document.body.innerHTML = dojo.byId('grid_'+ div_id).innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    confirmSubmit(div_id);	
	    	    
	}
	function confirmSubmit(div_id){
		/*if (confirm("តើ​អ្នកជំពាក់នេះពិតជាបានសងរួចហើយរឺទេ ?")){
			dijit.byId('frmlist_owe_'+ div_id).submit();			
		}*/
	}
</script>
<script type="text/javascript">
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
            store: sender_store,
            autoComplete: true,                        
            required: true,
            id: "sender_name",
            name: "sender_name",
            searchAttr: "name",
            value: "<?php echo $this->selected;?>",     
            class: 'fullside',            
            missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ផ្ញើរ!",            
            onChange: function() {                
            }
        }, "sender_name");
	}); 

</script>


<form name="frmlist_fund" action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rptowes')); ?>" dojoType="dijit.form.Form" method="post">
	<table width="100%">
		<tr>
			<td width="20%">
				<input id="sender_name" />	
					<br />
					<input type="submit" value="ស្វែង​រក" label="ស្វែង​រក" id="submitButton" 
						dojoType="dijit.form.Button"  iconClass="dijitIconSearch"/>
			</td>
			<td align="right">
			</td>
		</tr>
	</table>
</form>
<br/>

<?php if(!empty($this->owerlist['err']) && $this->owerlist['err']):?>
	<script type="text/javascript">
		alert("<?php echo $this->owerlist['msg']?>");
	</script>
	<table style="width: 100%; line-height: 25px;">		
		<tr>
			<td colspan="2" style="color: red; text-align: center;">
				<br/><br/>
				<?php echo $this->owerlist['msg']?>
			</td>
		</tr>
	</table>
	<br/><br/><br/>
<?php else:?>
<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
	showLabel="false" type="button" onclick="doPrint('1');">Print</button><br/>
<div id="grid_1" >
	<form name="frmlist_owe_1" id="frmlist_owe_1" dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'updateowe')); ?>"  method="post">
		<table style="width: 100%; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
			<?php $num=1; $l_ower = ''; $pa = '5px'; $row_id=1; $div_id=2; 
			$_total_dollar=0;$_total_bath=0;$_total_riel=0;
			?>	
			<?php if(!empty($this->owerlist))  foreach ( $this->owerlist as $key => $tran) { ?>
			
			<?php $ower = ($tran['sender_name']!="" ? $tran['sender_name'] : "Unknow");//not used if ($l_ower !== $ower){?>					
				<?php  if ($l_ower !== $ower){?>
				<?php if($key > 0) {
				?>	
					</table><br />
					<table style="width: auto; min-width:50%; float:right; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
						  <tr class="bgtop style-bold">
							  <td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់ជំពាក់សរុប($)&nbsp;</td>
							  <td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់ជំពាក់សរុប(B)&nbsp;</td>
							  <td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់ជំពាក់សរុប(R)&nbsp;</td>
						 </tr> 
						 <tr>
							  <td align="center" style="border:1px solid #000;"><b><?php echo $_total_dollar; ?></b></td>
							  <td align="center" style="border:1px solid #000;"><b><?php echo $_total_bath; ?></b></td>
							  <td align="center" style="border:1px solid #000;"><b><?php echo $_total_riel; ?></b></td>
						</tr>
				 </table>
					<br /><br /><br /><br /><br />
					<table style="width: 100%; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
	</form>
</div>
				<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
					showLabel="false" type="button" onclick="doPrint('<?php echo $div_id;?>');">Print</button><br/>
				<div id="grid_<?php echo $div_id;?>" >					
   <form name="frmlist_owe_<?php echo $div_id;?>" id="frmlist_owe_<?php echo $div_id;?>" dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rptowes')); ?>"  method="post">
				<?php $div_id++;?>
				<?php }  
				}//end if do print?>
			<?php  if ($l_ower !== $ower){?>
			<?php //$l_ower = $ower; $row_id=1; 
			?>
			<tr class="bgtop" height="40px">
				<td colspan="7" style="border:1px solid #000;">&nbsp;ឈ្មោះ <strong><?php echo $ower; ?></strong></td>
			</tr>
			<tr class="bgtop" align="center">
				<td><b style="font-size: 17px;">&nbsp;ល.រ&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;លេខប្រតិបត្តិការណ៏&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;ថ្ងែខែជំពាក់&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;ដុល្លា&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;បាត&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;រៀល&nbsp;</b></td>
				<td><b style="font-size: 17px;">&nbsp;ផ្សេងៗ&nbsp;</b></td>
			</tr>
			<?php 
			$l_ower = $ower; $row_id=1;?>
			
		<?php };//endif of->($l_ower != $tran['agentname'].$sub_agent)//good?>
			
		<?php 
		$amount_bath="";$amount_bath="";$amount_reil="";
				if($tran['amount_type']==1){ $_total_dollar= $_total_dollar+(empty($tran['amount_owe'])? 0 : $tran['amount_owe']);	
					$amount_dollar=(empty($tran['amount_owe'])? 0 : $tran['amount_owe']);
				}
				elseif($tran['amount_type']==2){$_total_bath= $_total_bath+(empty($tran['amount_owe'])? 0 : $tran['amount_owe']);
					$amount_bath=(empty($tran['amount_owe'])? 0 : $tran['amount_owe']);
				}
				else{$_total_riel= $_total_riel+(empty($tran['amount_owe'])? 0 : $tran['amount_owe']);
					$amount_reil =(empty($tran['amount_owe'])? 0 : $tran['amount_owe']);
				}
		?>
			<tr>
						<td class="td_line" style="padding-left: <?php echo $pa;?>; border:1px solid #000;"><?php echo $num;$num++;?></td>
						<td class="td_line" style="padding-left: <?php echo $pa;?>; border:1px solid #000"><?php echo $tran["invoice_no"];?>&nbsp;</td>
						<td class="td_line" style="padding-left: <?php echo $pa;?>; border:1px solid #000"><?php echo $tran["send_date"];?>&nbsp;</td>
						<td align="center" class="td_line" style="border:1px solid #000;"><strong><?php echo $amount_dollar;?></strong></td>
						<td align="center" class="td_line" style="border:1px solid #000;"><?php echo $amount_bath; ?></td>
						<td align="center" class="td_line" style="border:1px solid #000;"><strong><?php echo $amount_reil;?></strong></td>
						<td align="center" class="td_line" style="border:1px solid #000;"></td>
			 </tr>
			 
		<?php }//end forearch ?>
		</table><br />
		<table style="width: auto; min-width:50%; float:right; line-height: 25px; border:1px solid #000; border-collapse: collapse;" border="2px" cellspacing="2">
	 				<tr class="bgtop style-bold">
						  	<td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់ជំពាក់សរុប($)&nbsp;</td>
						  	<td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់ជំពាក់សរុប(B)&nbsp;</td>
						  	<td align="center" style="border:1px solid #000;">&nbsp;ប្រាក់ជំពាក់សរុប(R)&nbsp;</td>
					 </tr> 
					  <tr>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_total_dollar; ?></b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_total_bath; ?></b></td>
						  	<td align="center" style="border:1px solid #000;"><b><?php echo $_total_riel; ?></b></td>
					 </tr>
		</table><br/><br/>
	</form>
</div>

<iframe marginwidth="45" marginheight="45" name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php endif;?>