<?php
	$this->headTitle('Currency Smart | Report Current Balance page'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$session_user=new Zend_Session_Namespace('auth');
?>	
<style>
<!--
	.tbtable{		
		font-weight: bolder;
		line-height: 40px;
		text-align: center;
	}
	.tbtable .tbheader{
		background-color: #012a15;
		text-align: left;
		color: #fff;
	}
	.tbtable .first{
		background-color: #016315;
		color: #fff;
	}
	.tbtable .first td{
		width: 33.33%
	}
	.tbtable .second{
		background-color: #fff; 
		color: black;
	}
	.nevg-value{
		color: RED;
	}
	.tbtable .second .input-inner {
		margin: 0px;
		padding: 0px;
		width: 99%;	
		border: none;
	}
	
	#dollar.dijitInputInner, #bath.dijitInputInner, #rail.dijitInputInner{
		text-align: center;		
		background-color: #FFFFFF !important;
	}
	
	.bg-white{
		background-color: #FFFFFF !important;		
	}
}
-->
</style>
<?php if($session_user->level == 1): //Admin View Only?>
<form id='frm_search_capital' name='frm_search_capital' action="<?php echo $this->url(array('module'=>'reports','controller'=>'index','action'=>'rptsummary-transfer')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table class="fullside">
		<tr>
			<td>
				<label>ឈ្មោះ​អ្នក​ប្រើប្រាស់</label>
				<select style="text-align: left;" onchange="dijit.byId('frm_search_capital').submit();" name="user_id" id="select_user_id" dojoType="dijit.form.FilteringSelect" required="true">
					<option value="-1" <?php echo (-1 == $this->user_id)?"selected":"";?>>All</option> 
					<?php foreach ($this->users as $key => $u) : ?>
						<option value="<?php echo $u['id'];?>" <?php echo ($u['id'] == $this->user_id)?"selected":"";?>><?php echo  $u['name'];?></option>
					<?php endforeach;?> 
				</select>
			</td>
			<td align="right">
				ពី៖&nbsp;
				<input type="text" name="from_date" id="from_date" value="<?php echo $this->from_date;?>"
					dojoType="dijit.form.DateTextBox" style="height: 30px; width: 210px;" 
					rangeMessage="កាល​បរិច្ឆេទ  ពី មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ដល់"
					constraints="{datePattern:'dd/MM/yyyy', max:'<?php echo  $this->to_date;?>'}" 
					onchange="dijit.byId('to_date').constraints.min = arguments[0]; document.frm_search_capital.submit();" />
				ដល់៖&nbsp;
				<input type="text" name="to_date" id="to_date" value="<?php echo  date_format(date_create($this->to_date), "Y-m-d");?>" 
					dojoType="dijit.form.DateTextBox" style=" height: 30px; width: 195px;"
					rangeMessage='កាល​បរិច្ឆេទ  ដល់ មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ពី' 
					constraints="{min:'<?php echo date_format(date_create($this->from_date), "Y-m-d");?>', datePattern:'dd/MM/yyyy'}" 
					onChange="dijit.byId('from_date').constraints.max = arguments[0]; document.frm_search_capital.submit();" />
			</td>
		</tr>
	</table>
	
	
	
	
	<input type="hidden" name="actions" value="search">
</form>
<?php endif;?>

<?php if(!empty($this->tranlist['err']) && $this->tranlist['err']):?>
	<script type="text/javascript">
	<!--
		alert("<?php echo $this->tranlist['msg']?>");
	//-->
	</script>
	<style>
		.table_print{
			width: 100%; 
			line-height: 40px;
			font-size:12pt; 
		}
		.header{
			font-size: 16pt;
			font-weight: bolder;
			text-align: center;
		}
	</style>
	<table class="table_print">
		<tr>
			<td class="header">បញ្ចីសរុបចំនួនទឹក​ប្រាក់​  - វេ</td>
		</tr>
		<tr>
			<td style="color: red; text-align: center;">
				<br/><br/>
				<?php echo $this->tranlist['msg']?>
			</td>
		</tr>
	</table>
	<br/><br/><br/>
<?php else:?>
<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
	showLabel="false" type="button" onclick="doPrint();">Print</button><br/>
<div id="grid" >
	<style>
		.lblname{
			padding-left: 20px;
			text-align: left !important;
			background-color: #C3C2C2;
			font-weight: bolder;
		}
		.lblsymbol{
			padding-left: 20px;
			text-align: left !important;
			background-color: #F7F6F6;
			font-weight: bolder;
		}
		.lblsummary{
			background-color: #999999;
			color: #ffffff;
			font-weight: bolder;
		}
		.header{
			font-size: 16pt;
			font-weight: bolder;
			text-align: center;
		}
		.sub-header{
			font-weight: bolder;
			text-align: center;
		}
		.table_print{
			width: 100%; 
			line-height: 40px;
			font-size:12pt; 
		}
		.table_print table{
			width: 100%;
			margin-bottom: 10px;
		}
		.table_print table th{
			font-weight: bolder;
			text-align: center;
		}
		.table_print table th.no{
			width: auto;
		}
		
		.table_print table th.name{
			width: 25%;
		}
		
		.table_print table th{
			width: 35%;
		}
		
		.table_print table td.amount{
			text-align: right;
			padding-right: 10px;
		}
		
		.table_print table td.labeltotal{
			text-align: center;	
			background-color: #C3C2C2;
			font-weight: bolder;
		}
		
		.table_print table td{
			text-align: left;
			padding-left: 10px;
		}
		
	</style>
	<table class="table_print">
		<tr>
			<td class="header">បញ្ចីសរុបចំនួនទឹក​ប្រាក់​  - វេ </td>
		</tr>
		<tr>
			<td class="sub-header"><?php echo date_format(date_create($this->from_date), "d-m-Y")." - ".date_format(date_create($this->to_date), "d-m-Y") ;?></td>
		</tr>
		<tr>
			<td colspan="2">
				<?php 
					$no=1;
					$tt_user=array(array('d'=>0,'b'=>0,'r'=>0),array('d'=>0,'b'=>0,'r'=>0));
					$l_name = $this->tranlist[0]['username'];
					$l_currency = $this->tranlist[0]['currncytype'];
					$l_ttype = $this->tranlist[0]['tran_type'];			
 					$label_type = array("ផ្ញើរ","ទទួល");
				?>
				<table border="1" cellspacing="0">
					<tr>
						<td colspan="5" class="lblname"><?php echo $l_name;?></td>
					</tr>
					<tr>
						<th class="no">លេខ </th>
						<th class="name">ឈ្មោះ​អ្នក​ផ្ញើរ</th>
						<th class="name">ឈ្មោះ​អ្នក​ទទួល</th>
						<th class="name">លេខ​អ្នក​ទទួល</th>
						<th>ចំនួន​ទឹក​ប្រាក់</th>
					</tr>
					<tr>
						<td colspan="5" class="lblname"><?php echo $label_type[$l_ttype];?></td>
					</tr>
					<tr>
						<td colspan="5" class="lblsymbol"><?php echo $l_currency.  " " .$this->tranlist[0]['currncysymbol'];?></td>
					</tr>
					<?php foreach ( $this->tranlist as $key => $tran) : ?>
						<?php if($tran['username'] != $l_name):?>							
							</table>
							<table border="1" cellspacing="0" class="table" >
								<tr>
									<td rowspan="2" class='labeltotal'>ប្រភេទ</td>
									<td colspan="2" class='labeltotal'>មុន​ទូទាត់</td>
									<td colspan="2" class='labeltotal'>ក្រោយ​ទូទាត់</td>										
								</tr>
								<tr>
									<td class='labeltotal'><?php echo $this->keycode['rpt-transfer-send-kh'].' '.$this->keycode['mainbranch'];?></td>
									<td class='labeltotal'><?php echo $this->keycode['rpt-transfer-send-kh'].' '.$l_name;?></td>
									<td class='labeltotal'><?php echo 'នៅ​ខ្វះ '.$this->keycode['mainbranch'];?></td>
									<td class='labeltotal'><?php echo 'នៅ​ខ្វះ '.$l_name;?></td>										
								</tr>
								<tr>
									<td class='labeltotal'>ដុល្លា</td>
									<td class="amount">$ <?php echo number_format($tt_user[1]["d"],(!strrpos($tt_user[1]["d"],"."))? 0 : 2);?></td>
									<td class="amount">$ <?php echo number_format($tt_user[0]["d"],(!strrpos($tt_user[0]["d"],"."))? 0 : 2);?></td>
									<?php $_us = $tt_user[1]["d"] - $tt_user[0]["d"]?>
									<td class="amount">$ <?php echo number_format(($_us < 0)? 0 : $_us,(!strrpos($_us,"."))? 0 : 2);?></td>
									<td class="amount">$ <?php echo number_format(($_us >0)? 0: abs($_us),(!strrpos(abs($_us),"."))? 0 : 2);?></td>
								</tr>
								<tr>
									<td class='labeltotal'>បាត</td>
									<td class="amount">B <?php echo number_format($tt_user[1]["b"],(!strrpos($tt_user[1]["b"],"."))? 0 : 2);?></td>
									<td class="amount">B <?php echo number_format($tt_user[0]["b"],(!strrpos($tt_user[0]["b"],"."))? 0 : 2);?></td>
									<?php $_bt = $tt_user[1]["b"] - $tt_user[0]["b"]?>
									<td class="amount">B <?php echo number_format(($_bt < 0)? 0 : $_bt,(!strrpos($_bt,"."))? 0 : 2);?></td>
									<td class="amount">B <?php echo number_format(($_bt >0)? 0: abs($_bt),(!strrpos(abs($_bt),"."))? 0 : 2);?></td>
								</tr>
								<tr>
									<td class='labeltotal'>រៀល</td>
									<td class="amount">R <?php echo number_format($tt_user[1]["r"],(!strrpos($tt_user[1]["r"],"."))? 0 : 2);?></td>
									<td class="amount">R <?php echo number_format($tt_user[0]["r"],(!strrpos($tt_user[0]["r"],"."))? 0 : 2);?></td>
									<?php $_r = $tt_user[1]["r"] - $tt_user[0]["r"]?>
									<td class="amount">R <?php echo number_format(($_r < 0)? 0 : $_r,(!strrpos($_r,"."))? 0 : 2);?></td>
									<td class="amount">R <?php echo number_format(($_r > 0)? 0: abs($_r),(!strrpos(abs($_r),"."))? 0 : 2);?></td>
								</tr>								
							</table><br/><br/>
							<?php $l_name = $tran['username']; $tt_user=array(array('d'=>0,'b'=>0,'r'=>0),array('d'=>0,'b'=>0,'r'=>0));?>
							<table border="1" cellspacing="0">
								<tr>
									<td colspan="5" class="lblname"><?php echo $l_name;?></td>
								</tr>
								<tr>
									<th class="no">លេខ </th>
									<th class="name">ឈ្មោះ​អ្នក​ផ្ញើរ</th>
									<th class="name">ឈ្មោះ​អ្នក​ទទួល</th>
									<th class="name">លេខ​អ្នក​ទទួល</th>
									<th>ចំនួន​ទឹក​ប្រាក់</th>
								</tr>
						<?php endif;?>
						<?php if($tran['tran_type'] != $l_ttype):?>
							<?php $l_ttype = $tran['tran_type'];?>
							<tr>
								<td colspan="5" class="lblname"><?php echo $label_type[$l_ttype];?></td>
							</tr>
						<?php endif;?>	
						<?php if($tran['currncytype'] != $l_currency):?>
							<?php $l_currency = $tran['currncytype'];?>
							<tr>
								<td colspan="5" class="lblsymbol"><?php echo $l_currency.  " " .$tran['currncysymbol'];?></td>
							</tr>
						<?php endif;?>		
						<?php 
							$total_money = $tran['total_money'];
// 							if($tran['tran_type'] == 1){
// 								$total_money *= -1;
// 							}
						?>
							<tr>
								<td><?php echo $no++;?></td>
								<td><?php echo empty($tran['sender_name'])?'&nbsp;':$tran['sender_name']?></td>
								<td><?php echo empty($tran['reciever_name'])?'&nbsp;':$tran['reciever_name']?></td>
								<td><?php echo $tran['reciever_tel']?></td>
								<td class="amount"><?php echo  $tran['currncysymbol'] ." ".number_format($total_money,(!strrpos($total_money,"."))? 0 : 2);?></td>
							</tr>
							<?php 
								if($tran['currncysymbol'] == "$"){
									$tt_user[$l_ttype]['d'] += $total_money;
								}
								elseif($tran['currncysymbol'] == "B"){
									$tt_user[$l_ttype]['b'] += $total_money;
								}
								elseif($tran['currncysymbol'] == "R"){
									$tt_user[$l_ttype]['r'] += $total_money;
								}
							?>
						<?php endforeach; ?>	
				</table>
				<table border="1" cellspacing="0" class="table" >
					<tr>
						<td rowspan="2" class='labeltotal'>ប្រភេទ</td>
						<td colspan="2" class='labeltotal'>មុន​ទូទាត់</td>
						<td colspan="2" class='labeltotal'>ក្រោយ​ទូទាត់</td>										
					</tr>
					<tr>
						<td class='labeltotal'><?php echo $this->keycode['rpt-transfer-send-kh'].' '.$this->keycode['mainbranch'];?></td>
						<td class='labeltotal'><?php echo $this->keycode['rpt-transfer-send-kh'].' '.$l_name;?></td>
						<td class='labeltotal'><?php echo $this->keycode['mainbranch'].' នៅ​ខ្វះ';?></td>
						<td class='labeltotal'><?php echo $l_name.' នៅ​ខ្វះ';?></td>										
					</tr>
					<tr>
						<td class='labeltotal'>ដុល្លា</td>
						<td class="amount">$ <?php echo number_format($tt_user[1]["d"],(!strrpos($tt_user[1]["d"],"."))? 0 : 2);?></td>
						<td class="amount">$ <?php echo number_format($tt_user[0]["d"],(!strrpos($tt_user[0]["d"],"."))? 0 : 2);?></td>
						<?php $_us = $tt_user[1]["d"] - $tt_user[0]["d"]?>
						<td class="amount">$ <?php echo ($_us < 0)? 0 : number_format($_us,(!strrpos($_us,"."))? 0 : 2);?></td>
						<td class="amount">$ <?php echo ($_us >0)? 0: number_format(abs($_us),(!strrpos(abs($_us),"."))? 0 : 2);?></td>
					</tr>
					<tr>
						<td class='labeltotal'>បាត</td>
						<td class="amount">B <?php echo number_format($tt_user[1]["b"],(!strrpos($tt_user[1]["b"],"."))? 0 : 2);?></td>
						<td class="amount">B <?php echo number_format($tt_user[0]["b"],(!strrpos($tt_user[0]["b"],"."))? 0 : 2);?></td>
						<?php $_bt = $tt_user[1]["b"] - $tt_user[0]["b"]?>
						<td class="amount">B <?php echo ($_bt < 0)? 0 : number_format($_bt,(!strrpos($_bt,"."))? 0 : 2);?></td>
						<td class="amount">B <?php echo ($_bt >0)? 0: number_format(abs($_bt),(!strrpos(abs($_bt),"."))? 0 : 2);?></td>
					</tr>
					<tr>
						<td class='labeltotal'>រៀល</td>
						<td class="amount">R <?php echo number_format($tt_user[1]["r"],(!strrpos($tt_user[1]["r"],"."))? 0 : 2);?></td>
						<td class="amount">R <?php echo number_format($tt_user[0]["r"],(!strrpos($tt_user[0]["r"],"."))? 0 : 2);?></td>
						<?php $_r = $tt_user[1]["r"] - $tt_user[0]["r"]?>
						<td class="amount">R <?php echo ($_r < 0)? 0 : number_format($_r,(!strrpos($_r,"."))? 0 : 2);?></td>
						<td class="amount">R <?php echo ($_r > 0)? 0: number_format(abs($_r),(!strrpos(abs($_r),"."))? 0 : 2);?></td>
					</tr>								
				</table>		
			</td>
		</tr>
	</table>
</div>

<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php endif;?>

<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');

	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML = dojo.byId('grid').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();	    
	}	
</script>