<?php
	$this->headTitle('Currency Smart | Sub Agent edit page'); 
	echo $this->headTitle();
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>

<form action="<?php echo $this->url(array('module'=>'subagent','controller'=>'index','action'=>'edited')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}

			return false;
	</script>
		
	<table cellspacing="20" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន ទំនាក់ទំនង របស់​ភ្នាក់ងារ</strong></legend>
					<table cellspacing="20" width="100%">
						<tr>
							<td align="center" valign="top">
								<table>
									<tr>
										<td>ឈ្មោះ​​សាខា​មេ</td>
										<td>
											<select name="agent_id" id="agent_id" class='fullside' dojoType="dijit.form.FilteringSelect" missingMessage="អ្នក​ភ្លេច​បំពេញ​  ឈ្មោះ​​សាខា​មេ!">												 
												<?php foreach ($this->agentlist as $key => $ag) : ?>
													<option value="<?php echo $ag['id'];?>" <?php if($this->subagent_edit['agent_id'] == 0) echo 'selected';?> ><?php echo $ag['name'];?></option>
												<?php endforeach;?>	 
											</select>
										</td>
									</tr>
									<tr>
										<td>ឈ្មោះ​​សាខា​មេ</td>
										<td>
											<input type="text" required="true" name="sub_agent_name" id="sub_agent_name" placeholder="ឈ្មោះ​ភ្នាក់​ងារ" value="<?php echo $this->subagent_edit['name'];?>"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​​ភ្នាក់ងារ!" class='fullside'/>
										</td>
									</tr>	
									<tr>
										<td>ក្បែរ</td>
										<td>
											<input type="text" required="false" name="block" id="block" placeholder="ឈ្មោះ​ទីកន្លែង ក្បែរ ផ្ទះ​របស់អ្នក" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->subagent_edit['block'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​ទីកន្លែង ក្បែរ ផ្ទះ​របស់អ្នក!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>លេខ​ផ្ទះ</td>							
										<td>
											<input type="text" required="false" name="house_no" id="house_no" placeholder="លេខ​ផ្ទះ" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->subagent_edit['house_no'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ លេខ​ផ្ទះ!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>លេខ​ក្រុម</td>
										<td>
											<input type="text" required="false" name="group_no" id="group_no" placeholder="លេខ​ក្រុម" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->subagent_edit['group_no'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ លេខ​ក្រុម!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>លេខ​ផ្លូវ</td>
										<td>
											<input type="text" required="false" name="street_no" id="street_no" placeholder="លេខ​ផ្លូវ" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->subagent_edit['street_no'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ លេខ​ផ្លូវ!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>ឃុំ/សង្កាត់</td>							
										<td>
											<input type="text" required="false" name="sangkat" id="sangkat" placeholder="ឃុំ/សង្កាត់" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->subagent_edit['sangkat'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>ស្រុក/​ខ័ណ្ឌ</td>
										<td>
											<input type="text" required="false" name="khan" id="khan" placeholder="ស្រុក/​ខ័ណ្ឌ" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->subagent_edit['khan'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ ស្រុក/​ខ័ណ្ឌ!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>ខេត្ត/ក្រុង</td>
										<td>
											<select name="province" required="true" id="province" class='fullside' dojoType="dijit.form.FilteringSelect" missingMessage="អ្នក​ភ្លេច​បំពេញ​  ខេត្ត/ក្រុង​!"> 
												<?php foreach ($this->provinces as $key => $pro) : ?>
													<option value="<?php echo $pro['id'];?>" <?php if($this->subagent_edit['province'] == $pro['id']) echo 'selected';?> ><?php echo $pro['name'];?></option>
												<?php endforeach;?>									
											</select> 
										</td>
									</tr>
								</table>
							</td>
							<td valign="top" align="center">
								<table>
									<tr>
										<td>លេខ​កូដ</td>
										<td>
											<input type="text" required="false" name="code" id="code" placeholder="លេខ​កូដ" maxlength="6"
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->subagent_edit['code'];?>"
											missingMessage="អ្នក​ភ្លេច​បំពេញ​ លេខ​កូដ!" class='fullside'/>
										</td>
									</tr>
									<tr>
										<td>លេខ​ទូរស័ព្ទ</td>
										<td>
											<input type="text" id="tel" placeholder="លេខ​ទូរស័ព្ទ"  class='fullside'
											 data-dojo-Type="dijit.form.ValidationTextBox"   
											data-dojo-props="regExp:'[0-9]{9,10}', required: true, 
															 invalidMessage:'លេខ​ទូរស័ព្ទ​​ មិន​ត្រឹម​ត្រូវទេ. មិនមាន​  ចន្លោះ ឬ សញ្ញា​ពិសេស.',
															 value: '<?php echo $this->subagent_edit['tel'];?>',
															 missingMessage:'អ្នក​ភ្លេច​បំពេញ​ លេខ​ទូរស័ព្ទ!',
															 name:'tel'"/>
										</td>
									</tr>
									<tr>
										<td>លេខ​ទូរស័ព្ទ Fax</td>
										<td>
											<input type="text" id="fax" placeholder="លេខ​ទូរស័ព្ទ Fax"  class='fullside'
											 data-dojo-Type="dijit.form.ValidationTextBox"   
											data-dojo-props="regExp:'[0-9]{9,10}', required: false, 
															 invalidMessage:'លេខ​ទូរស័ព្ទ​​ មិន​ត្រឹម​ត្រូវទេ. មិនមាន​  ចន្លោះ ឬ សញ្ញា​ពិសេស.',
															 value: '<?php echo $this->subagent_edit['fax'];?>',
															 missingMessage:'អ្នក​ភ្លេច​បំពេញ​ លេខ​ទូរស័ព្ទ Fax!',
															 name:'fax'"/>
										</td>
									</tr>
									<tr>
										<td>លេខ​ទូរស័ព្ទដៃ</td>
										<td>
											<input type="text" id="hp" placeholder="លេខ​ទូរស័ព្ទដៃ"  class='fullside'
											 data-dojo-Type="dijit.form.ValidationTextBox"   
											data-dojo-props="regExp:'[0-9]{9,10}', required: false, 
															 invalidMessage:'លេខ​ទូរស័ព្ទ​​ មិន​ត្រឹម​ត្រូវទេ. មិនមាន​  ចន្លោះ ឬ សញ្ញា​ពិសេស.',
															 value: '<?php echo $this->subagent_edit['hp'];?>',
															 missingMessage:'អ្នក​ភ្លេច​បំពេញ​ លេខ​ទូរស័ព្ទដៃ!',
															 name:'hp'"/>
										</td>
									</tr>
									<tr>
										<td>ស្ថាន​ភាព</td>
										<td>
											<select name="active" required="true" id="active" dojoType="dijit.form.FilteringSelect" class='fullside'> 
												<option value="1" <?php if($this->subagent_edit['active'] == 1) echo 'selected';?> >ប្រើ​ប្រាស់</option>
												<option value="0" <?php if($this->subagent_edit['active'] == 0) echo 'selected';?> >មិនប្រើ​ប្រាស់</option>																					
											</select> 
										</td>
									</tr>								
								</table>
							</td>
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>	
	<input type="hidden" name="id" value="<?php echo  $this->subagent_edit['id']?>"/>
</form>