<?php
	$this->headTitle('Currency Smart | Add loan page'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<style>
fieldset{
	border-color: rgba(7, 171, 44, 1) -moz-use-text-color;
}
</style>
<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
<script src="<?php echo $base_url;?>js/moment.min.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.form.CheckBox");     
	dojo.require("dojo.number");
	dojo.require('dojox.form.BusyButton');
	dojo.require("dijit.Dialog");

	var sender_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->sender));?> );
	
	dojo.ready(function(){

		desabledInterest();//for disabled All Interest
		
		var tel = dojo.byId("tel"); 
		dojo.connect(tel, "onkeyup", function(evt){	
			var filtercode= function(items, request){
			  if(items.length){
				 dijit.byId('sender').attr( 'value',sender_store.getValue(items[0],'id'));
			  }
		  	};		  
		  
		  var request = sender_store.fetch({query: {tel: this.value}, queryOptions: {ignoreCase: true}, onComplete: filtercode});
		});

	
		
		new dijit.form.FilteringSelect({
            store: sender_store,
            autoComplete: true,                        
            required: true,
            id: "sender",
            name: "sender",
            searchAttr: "name",           
            class: 'fullside',            
            missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ខ្ចី!",            
            onChange: function() {
            	checkSender();
            }
        }, "sender");	
	});   
</script>
<script type="text/javascript">
function CheckIsAllInterest(){
	all_interest = dijit.byId("all_interest");
	if(all_interest.checked){
		desabledInterest();
	}else{
		enabledInterest();
	}
}
function desabledInterest(){
	dijit.byId('interest_dollar').set('readOnly',true);		
	dijit.byId('interest_bath').set('readOnly',true);		
	dijit.byId('interest_riel').set('readOnly',true);	

	dijit.byId('total_interest').attr('value',2);	
	dijit.byId('total_interest').set('readOnly',false);	

	dijit.byId('interest_dollar').attr('value','');		
	dijit.byId('interest_bath').attr('value','');		
	dijit.byId('interest_riel').attr('value','');		
}
function enabledInterest(){
	dijit.byId('interest_dollar').set('readOnly',false);		
	dijit.byId('interest_bath').set('readOnly',false);		
	dijit.byId('interest_riel').set('readOnly',false);	
	dijit.byId('total_interest').attr('value','');	
	dijit.byId('total_interest').set('readOnly',true);	

	

	dijit.byId('interest_dollar').attr('value',2);		
	dijit.byId('interest_bath').attr('value',2);		
	dijit.byId('interest_riel').attr('value',2);		
}
function checkSender(){
	dijit.byId('debt_dollar').attr('value',0);
	dijit.byId('debt_bath').attr('value',0);
	dijit.byId('debt_khmer').attr('value',0);
	 sender=dijit.byId('sender').get('value');
	if(sender==-1){
		dijit.byId("popupsender").show();
	}else{
		setValueToOther();
		getAllDebtBySender(sender);
	} 
}	
	function printSave(){		
		/*if(dijit.byId('frm_add_tran').validate()) {
			draw_dollar = dijit.byId('withdraw_dollar').get('value');
			draw_bath = dijit.byId('withdraw_bath').get('value');
			draw_riel = dijit.byId('withdraw_riel').get('value');
			
			if((draw_dollar <=0 && draw_bath <=0 && draw_riel <=0 ) || (isNaN(draw_dollar) && isNaN(draw_bath) && isNaN(draw_riel) ) ){
				alert('សូម​ពិនិត្រ ទឹកប្រាក់​​ដែល​​ត្រូវដក​ម្តង ​ទៀត...!');
				dijit.byId('withdraw_dollar').focus();
				return false;
			}else{
			showDialog();			}
		}*/
		showDialog();	
	}
	function setValueToOther(){
		if(dijit.byId('sender').item != null){	
			sender_tel = dijit.byId('sender').item.tel;
			dijit.byId("tel").attr('value', sender_tel);	
		}
	}

var url_getallmoney = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-amount')); ?>';//for get payout date of sender 
function getAllDebtBySender(sender_id){
				dojo.xhrPost({
			    url: url_getallmoney,	
			    content : { 
					'sender_id': sender_id,
						  },		    
				handleAs:"json", 
			    load: function(response) {	
			    	dojo.byId('lbl_showpopup').innerHTML = 'ជំពាក់ប្រាក់ដើម ';
				    tem='';
				    tem+='<tr class="bgtop" align="center" style="height: 25px; background: none repeat scroll 0% 0% #C3C2C2; font-weight: bold; font-size: 13px;">';
				    tem+='<td>&nbsp;ល.រ &nbsp;</td>';
				    tem+='<td>&nbsp;ប្រភេទ.&nbsp;</td>';
				    tem+='<td>&nbsp;លេខប្រតិ.&nbsp;</td>';
				    tem+='<td>&nbsp;ថ្ងែខែជំពាក់ &nbsp;</td>';
				    tem+='<td>&nbsp;ប្រាក់ &nbsp;</td>';
				    tem+='<td>&nbsp;ជំពាក់ថ្មី &nbsp;</td>';
				    tem+='<td>&nbsp;ប្រាក់ដើមសរុប &nbsp;</td>';
				  	tem+='<td>&nbsp;ការប្រាក់/ខែ&nbsp;</td>';
				  	tem+='<td>&nbsp;រយៈពេល&nbsp;</td>';
				  	tem+='<td>&nbsp;ចំនួនការប្រាក់&nbsp; </td>';
				    tem+='<td>&nbsp;សរុប&nbsp; </td>';
				    tem+='</tr>';
				    total_per_tran=0;
				    _index = 0;
				    is_set = '';
				   for(i=0; i<response.length;i++){
					   _index++;
					   total_rate=0;
					  // total_new_debt=0;
					   amount_rate = 0;
					   //
						data = response[i];
					if(response.length==1){
							   
							end = '<?php echo date('Y-m-d');?>';
							day = countDays(data.loan_date,end);
							
							amount_rate=0;
							total_new_debt = data.loan_amount;
							total_per_tran=calculateMoneyWithRate(day,total_new_debt,((data.laon_rate/100)/30));//amount day,capital,rate
							if(total_per_tran!=0){
								amount_rate = total_per_tran-total_new_debt;
								
							}else{
								total_per_tran = total_new_debt;
							}
							 if(data.currency_type==1){
									str_curr= "ដុល្លា";
									dijit.byId('debt_dollar').attr('value',total_per_tran);
									
							}else if(data.currency_type==2){
									str_curr= "បាត";
									dijit.byId('debt_bath').attr('value',total_per_tran);
							}else{
									str_curr= "រៀល";
									dijit.byId('debt_khmer').attr('value',total_per_tran);
							}
							 s_status = 'ជំពាក់';
							if(data.status==2){
								s_status = 'នៅសល់';
							}
						}else{
								/*if(i+1==response.length){
									end = '<?php //echo date('Y-m-d');?>';
								}else{
									end = response[i+1].loan_date;
								}
								day = countDays(data.loan_date,end);*/
								
								if(i>0){
									if(is_set==data.currency_type){
										/////////////////
										if(i+1==response.length){ //if end record
											end = '<?php echo date('Y-m-d');?>';
										}else{
											if(data.currency_type!=response[i+1].currency_type){//if record 1!= record 2
												end = '<?php echo date('Y-m-d');?>'; //check condition sen
											}else{
												end = response[i+1].loan_date;
											}
										}
										day = countDays(data.loan_date,end);//////////////////////
										
										tem_debt = total_per_tran;
										amount_rate=0;
										
									    total_new_debt = dojo.number.round(data.loan_amount,2)+tem_debt;//ប្រាក់ដើមបន្ទាប់
										total_per_tran=dojo.number.round(calculateMoneyWithRate(day,total_new_debt,((data.laon_rate/100)/30)),2);//amount day,capital,rate
										if(total_per_tran!=0){
											amount_rate = total_per_tran-total_new_debt;//if amount day more than 1
										}else{
											total_per_tran = total_new_debt; //amount =0;
										}
										is_set=response[i].currency_type;
									}else{
										if(i+1==response.length){ //if end record
											end = '<?php echo date('Y-m-d');?>';
										}else{
											if(data.currency_type!=response[i+1].currency_type){//if record 1!= record 2
												end = '<?php echo date('Y-m-d');?>'; //check condition sen
											}else{
												end = response[i+1].loan_date;
											}
										}
										day = countDays(data.loan_date,end);//////////////////////
										///////////////////////condition with other currencty
										total_new_debt = dojo.number.round(data.loan_amount,2);
										amount_rate =dojo.number.round(day*(total_new_debt*data.laon_rate/100/30),2);//ការប្រាក់ក្នុងcurrent Tran
										total_per_tran =dojo.number.round(amount_rate+(total_new_debt),2);
										is_set=response[i].currency_type;
									}
								}else{//if the first record
									if(data.currency_type != response[i+1].currency_type){//if record 1!= record 2
										end = '<?php echo date('Y-m-d');?>'; //check condition sen
									}else{
										end = response[i+1].loan_date;
									}
									day = countDays(data.loan_date,end);
									
									amount_rate=0;
									total_new_debt = dojo.number.round(data.loan_amount,2);
									total_per_tran=dojo.number.round(calculateMoneyWithRate(day,total_new_debt,((data.laon_rate/100)/30)),2);//amount day,capital,rate
									if(total_per_tran!=0){
										amount_rate = dojo.number.round((total_per_tran-total_new_debt),2);//if amount day more than 1
										
									}else{
										total_per_tran = total_new_debt;
									}
									tem_day_dollar = end;//end of first end day
									is_set=response[i].currency_type;
								}
								if(response[i].currency_type==1){
										dijit.byId('debt_dollar').attr('value',total_per_tran);
										str_curr= "ដុល្លា";
									//	tmp_date_d = data.loan_date;
										
								}else if(data.currency_type==2){
										dijit.byId('debt_bath').attr('value',total_per_tran); 
										str_curr= "បាត";
										//tmp_date_b = data.loan_date;
								}else{
										dijit.byId('debt_khmer').attr('value',total_per_tran);
										str_curr= "រៀល";
										//tmp_date_r = data.loan_date ;
								}
								s_status = 'ជំពាក់';
								if(data.status==2){
									s_status = 'នៅសល់';
								}
								
						}
					//date start,from
					var a = new Date(data.loan_date);
					var dd = a.getDate();
					s_fordate= 'ថ្ងៃទី '+dd+'ដល់ '+end;
					    tem+= '<tr>';
					    tem += '<td>&nbsp;'+_index+'</td>';
					    tem += '<td style="font-size:11px;">&nbsp;'+s_status+'&nbsp;</td>';
					    tem += '<td>&nbsp;'+data.invoice+'&nbsp;</td>';
					    tem += '<td style="font-size:14px;white-space: nowrap;">&nbsp;'+s_fordate+'&nbsp;</td>';
					    tem += '<td style="font-size:12px;">&nbsp;'+str_curr+'&nbsp;</td>';
					    tem += '<td>&nbsp;'+dojo.number.format(data.loan_amount)+'&nbsp;</td>';
					    tem += '<td>&nbsp;'+dojo.number.format(total_new_debt)+'&nbsp;</td>';
					    tem += '<td>&nbsp;'+data.laon_rate+' % &nbsp;</td>';
					    tem += '<td style="font-size:12px;">&nbsp;'+day+' ថ្ងៃ &nbsp;</td>';
						tem += '<td>&nbsp;'+dojo.number.format(amount_rate)+'&nbsp;</td>';
					    tem += '<td>&nbsp;'+dojo.number.format(total_per_tran)+' &nbsp;</td>';
					    tem += '</tr>';
					}
					amount_debt_dollar = dijit.byId('debt_dollar').get('value');
					amount_debt_bath = dijit.byId('debt_bath').get('value');
					amount_debt_riel = dijit.byId('debt_khmer').get('value');

					amount_debt_dollar = amount_debt_dollar.toString();
					amount_debt_bath = amount_debt_bath.toString();
					amount_debt_riel = amount_debt_riel.toString();
					
					var dot = amount_debt_dollar.indexOf('.');
					 if (dot == -1){	
						 result= read_money_in_khmer(amount_debt_dollar)+"​ ដុល្លាគត់"; 	
					 }else{
						   var temp = amount_debt_dollar.split('.');
					       var before_dot = read_money_in_khmer(temp[0]);
					       var after_doc = read_money_in_khmer(temp[1]);
					       result= before_dot + "ដុល្លាអាមេរិក និង"+after_doc+"សេន"; 	
					}
					result_bath='';
					var dot_b = amount_debt_bath.indexOf('.');
					if (dot_b == -1) {	
						 result_bath= read_money_in_khmer(amount_debt_bath)+"​ បាតគត់"; 	
					 }else{
						   var temp = amount_debt_bath.split('.');
					       var before_dot = read_money_in_khmer(temp[0]);
					       var after_doc = read_money_in_khmer(temp[1]);
					       result_bath= before_dot + "ក្បៀស"+after_doc+"​បាត"; 	
					}
					
				    tem+= '<tr style="border-bottom:none !important;">';
				    tem += '<td colspan="9" rowspan="3" style="border-bottom:none !important; border-left: medium none;"></td>';
					tem += '<td class="bgtop bg-box">&nbsp;សរុបជាដុល្លា($)&nbsp;</td>';
				    tem += '<td class="bgtop bg-box">&nbsp;'+dojo.number.format(amount_debt_dollar)+' &nbsp;</td>';
				    tem += '</tr>';
				    tem+= '<tr>';
					tem += '<td class="bgtop bg-box" align="left" >&nbsp;សរុបជាបាត(B)&nbsp;</td>';
				    tem += '<td class="bgtop bg-box" align="left" >&nbsp;'+dojo.number.format(amount_debt_bath)+' &nbsp;</td>';
				    tem += '</tr>';
				    tem+= '<tr>';
					tem += '<td class="bgtop bg-box" align="left">&nbsp;សរុបជារៀល(R)&nbsp;</td>';
				    tem += '<td class="bgtop bg-box" align="left">&nbsp;'+dojo.number.format(amount_debt_riel)+' &nbsp;</td>';
				    tem += '</tr>';
				   dojo.html.set(dojo.byId("show_rpt"),tem , {
					    parseContent: true,
					     
					});
					
				},
				error: function(e) {
					 alert(e);
				}
			}); 
}
function countAmountDay(start,end){
	days=countDays(start,end);
	return days;
}
function countDays(start,end){
var durationperday = 24 * 60 * 60 * 1000;
var s_date= moment(start,'YYYY M D');
var e_date= moment(end,'YYYY M D');
var days = moment.duration(e_date - s_date);

var amount_day = (days / durationperday);
return amount_day;

}
function calculateMoneyWithRate(amount_day,capital,rate){
	amount = dojo.number.round(capital,2)+dojo.number.round((capital*rate)*amount_day,2);
	return dojo.number.round(amount,2);
}
	function hideDialog() {		
		dijit.byId("terms").hide();
		dijit.byId('frm_add_tran').submit();
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	function printReport() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint1').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	}
</script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>	
	<table cellspacing="20" width="100%">
		<tr>
			<td colspan="2">
				<center style="width:50%;text-align: center; margin:0 auto;" >
				<fieldset style="border:1px solid #ccc; height: 177px;">
				<legend><strong>អត្រាប្តូរប្រាក់</strong></legend>	
					<table width="100%" cellspacing="10">
						<tr>
								<td width="50%"><strong>ដុល្លា-បាត</strong></td>
								<td><input id="BD" name="BD" value="<?php echo $this->rate['BD'];?>"  type="text" dojoType="dijit.form.NumberTextBox" style="color: red;"
									constraints="{pattern: '#,###.##'}"  class="fullside" value="0" />
								</td>
							</tr>
							<tr>
								<td><strong>ដុល្លា-រៀល</strong></td>
								<td><input id="RD" name="RD" type="text" value="<?php echo $this->rate['RD'];?>" dojoType="dijit.form.NumberTextBox" style="color: red;"
									constraints="{ pattern: '#,###.##'}" placeholder="ដុល្លា"   class="fullside"
									value="0" invalidMessage="ចំនួន​ទឹកប្រាក់​មិន​ត្រឹម​ត្រូវ!" rangeMessage="ចំនួន​ទឹកប្រាក់មិន​អាច​ធំ​ជាង​លុយ​ជំពាក់​ទេ!" />
								</td>
							</tr>
							<tr>
								<td><strong>បាត-រៀល</strong></td>
								<td><input id="RB" name="RB" type="text" value="<?php echo $this->rate['RB'];?>" dojoType="dijit.form.NumberTextBox" style="color: red;"
									constraints="{ pattern: '#,###.##'}" placeholder="ដុល្លា"   class="fullside"
								    value="0" invalidMessage="ចំនួន​ទឹកប្រាក់​មិន​ត្រឹម​ត្រូវ!" rangeMessage="ចំនួន​ទឹកប្រាក់មិន​អាច​ធំ​ជាង​លុយ​ជំពាក់​ទេ!" />
							    </td>
							</tr>
					</table>
				</center>
			</td>
		</tr>
		<tr>
			<td colspan="2">	
				<fieldset style="height: 330px; border:1px solid #07AB2C ;">
					<legend><strong>ព័ត៏មានខ្ចីប្រាក់</strong></legend>			
					<table style="margin: 0 auto; width: 90%;" cellspacing='10'>
					<tr>
							<td>
								<input type="button" value="បញ្ជីជំពាក់" label="បញ្ជីជំពាក់" id="popup" dojoType="dijit.form.Button" 
										iconClass="dijitIconTable" onclick="showRptDebt();"/><label id='lbl_showpopup'></label>
							</td>
							<td><center>ជំពាក់($)</center><input id="debt_dollar" name="debt_dollar"  type="text" dojoType="dijit.form.NumberTextBox" style="color: red;"
													constraints="{pattern: '#,###.##'}"  class="fullside" value="0" readonly></td>
							<td><center>ជំពាក់(B)</center><input id="debt_bath" name="debt_bath" type="text" dojoType="dijit.form.NumberTextBox" style="color: red;"
												constraints="{ pattern: '#,###.##'}" placeholder="ដុល្លា"   class="fullside"
												value="0" invalidMessage="ចំនួន​ទឹកប្រាក់​មិន​ត្រឹម​ត្រូវ!" rangeMessage="ចំនួន​ទឹកប្រាក់មិន​អាច​ធំ​ជាង​លុយ​ជំពាក់​ទេ!" readonly></td>
							<td><center>ជំពាក់(៛)</center><input id="debt_khmer" name="debt_khmer" type="text" dojoType="dijit.form.NumberTextBox" style="color: red;"
													constraints="{ pattern: '#,###.##'}" placeholder="ដុល្លា"   class="fullside"
													value="0" invalidMessage="ចំនួន​ទឹកប្រាក់​មិន​ត្រឹម​ត្រូវ!" rangeMessage="ចំនួន​ទឹកប្រាក់មិន​អាច​ធំ​ជាង​លុយ​ជំពាក់​ទេ!" readonly>
									<br /><label id="lbl_debt_riel" class="small-font"></label></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>ការប្រាក់រួម <input id="all_interest" checked="checked" name="all_interest" onclick="CheckIsAllInterest();" dojoType="dijit.form.CheckBox" value="1" /></td>
							<td> <input type="text" name="total_interest" id="total_interest"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="
									name:'total_interest',
									value:2,
									class:'fullside',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់ត្រូវខ្ចី!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'"></td>
						</tr>
						<tr>
							<td>ឈ្មោះ​អ្នក​ខ្ចី</td>
							<td>
								<input id="sender" >
							</td>
							<td>ចំនួនទឹកប្រាក់ខ្ចី($)</td>
							<td>
								<input type="text" name="borrow_dollar" id="borrow_dollar"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="
									name:'borrow_dollar',
									class:'fullside',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់ត្រូវខ្ចី!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
								&nbsp;&nbsp;
							</td>
							<td>ការប្រាក់($) (%/ខែ)</td>
							<td><input type="text" name="interest_dollar" id="interest_dollar"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="value:2,
									name:'interest_dollar',
									class:'fullside',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់ត្រូវខ្ចី!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
								&nbsp;&nbsp;</td>
						</tr>
						<tr>
							<td>លេខទូរស័ព្ទ</td>
							<td>
								<input type="text" name="tel" id="tel" placeholder="លេខទូរស័ព្ទ" 
									dojoType="dijit.form.TextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ លេខទូរស័ព្ទ!" class="fullside"/>
							</td>
							<td>ចំនួនទឹកប្រាក់ខ្ចី(B)</td>
							<td>
								<input type="text" name='borrow_bath' id='borrow_bath'  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="
									name:'borrow_bath',
									class:'fullside',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់ត្រូវខ្ចី!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
								&nbsp;&nbsp;
								
							</td>
							<td>ការប្រាក់(B)​  (%/ខែ)</td>
							<td><input type="text" name="interest_bath" id="interest_bath"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="value:2,
									name:'interest_bath',
									class:'fullside',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់ត្រូវខ្ចី!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
								&nbsp;&nbsp;</td>
					    </tr>
						<tr>
							<td style="width: 150px">ថ្ងៃខ្ចីប្រាក់</td>
							<td>
								<?php									
								    $newdate = date('Y-m-d', mktime(date('h'), date('i'), date('s'), date('m'), date('d')+45, date('Y')));
								?>
								<input type="text" name="loan_date" id="loan_date" value="<?php echo  date("Y-m-d");?>" 
								dojoType="dijit.form.DateTextBox" required="true" missingMessage="អ្នក​ភ្លេច​បំពេញ​ កាល​បរិច្ឆេទ វេ!" 
								 rangeMessage='កាល​បរិច្ឆេទ  វេ មិន​អាច​តូច​ជាង កាល​បរិច្ឆេទ ផុតកំណត់​ ' class='fullside'
								constraints="{datePattern:'dd/MM/yyyy', max:'<?php echo  $newdate;?>'}" 
								onchange="dijit.byId('epx_date').constraints.min = arguments[0];"/>
							</td>
							<td>ចំនួនទឹកប្រាក់ខ្ចី(៛)</td>
							<td>
								<input type="text" name="borrow_riel" id="borrow_riel"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="
									name:'borrow_riel',
									class:'fullside',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់ត្រូវខ្ចី!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
								&nbsp;&nbsp;
							</td>
							<td>ការប្រាក់(៛)  (%/ខែ)</td>
							<td><input type="text" name="interest_riel" id="interest_riel"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="value:2,
									name:'interest_riel',
									class:'fullside',
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់ត្រូវខ្ចី!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
								&nbsp;&nbsp;</td>
						</tr>
						<tr>
							<td colspan="6" align="center">
								<br />
									<input type="button" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId('frm_add_tran').submit();"/>
									<input type="button" value="រក្សាទុក & បោះពុម្ព" label="រក្សាទុក & បោះពុម្ព" id="busyButton" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>	
				</fieldset>		
			</td>
		</tr>
		
	</table>
	<input type="hidden" name="invoice_no" value="<?php echo $this->invoice_no;?>">
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" data-dojo-props="title:'របាយការណ៍   ប្រាក់កម្ចី', onCancel:hideDialog" id="terms" >
		<div id="divPrint" style="width: 7cm; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 12px;	
				}
			.fontmedium{
					font-size: 10px;	
				}
				.fonttel{
					font-size: 11px;	
				}
				.pleft{
					width: 110px;	
				}
				.setstyle{ color: red; font-weight: 600;}
			</style>	
			<table style="width: 7cm; font-size: 8pt; padding: 0px; margin: 0px; line-height: 17px;">
				<tr>
					   	<td align="center" colspan="3">	
					   	<table  width="100%" cellspacing="0" cellpadding="0">
					   		<tr style="line-height:10px;">
					   			<td width="36%" rowspan="2" style="valign:top;"><img style="margin-top: 1px;" src="<?php echo $base_url;?>images/logobrand.jpg" height="34px;"/></td>
						   		<td width="35%" align="center"><strong style="font-size:16px;font-family:'KH Koulen';text-align:center"><?php echo $this->keycode['rpt-transfer-title-kh'];?></strong></td>
								<td width="32%" rowspan="2" style="valign:top;"><img style="align:top; float:right;" src="<?php echo $base_url;?>images/logo-right.png" height="34px;"/></td>
							</tr>
							<tr>
								<td align="center" style="font-family:'KH Koulen';white-space: nowrap;font-size:11px;font-weight:bold; text-align:center;"><b><?php echo $this->keycode['rpt-transfer-title-eng'];?></td>
					   		</tr>
					   	</table>
			            </td>	   	        
				   </tr> 
					<tr>
					   	<td align="center" colspan="3" style="font-family:'KH Koulen';"><?php echo $this->keycode['rpt-transfer-business-meaning-kh'];?></td>	   	        
					</tr>            
				   <tr>
						<td align="center" colspan="3" style="font-size: 8pt;">
							<?php echo $this->keycode['rpt-transfer-business-meaning-eng'];?><br/>
							<?php echo $this->keycode['rpt-transfer-location-adr-kh'];?><br/>
							<strong class="fontbig"><?php echo $this->keycode['rpt-transfer-tel-eng'];?></strong>
						</td>
				   </tr>
				   <tr>
					   	<td class="pleft" style="border-bottom:1px solid #000;"><strong style="font-size: 10px;"><label id="lblinvioice">ប័ណ្ណប្រាក់កម្ចី</label></strong></td>
						<td align="right" colspan="2" style="border-bottom:1px solid #000;">
							ឈ្មោះបុគ្គលិក៖ <?php print($this->user_name);?>
						</td>
				   </tr>
				   <tr>
						<td>ឈ្មោះ​អ្នក​ខ្ចី</td>
						<td>:</td>
						<td><label id="lblsendername"></label></td>
				   </tr>
				    <tr>
						<td>លេខទូរស័ព្ទ</td>
						<td>:</td>
						<td><label id="lblphone"></label></td>
				   </tr>
				   <tr>
						<td>ថ្ងៃដកប្រាក់	</td>
						<td>:</td>
						<td><label id="lblstartdate"></label></td>
				   </tr>
				   <tr>
						<td>ទឹកប្រាក់ខ្ចីជា($)​</td>
						<td>:</td>
						<td align="right" style="border:1px solid rgba(156, 158, 159, 1)">
							<b><label id="lblborrow_dollar" class="fontmedium"></label><label id="lblrate_dollar" class="fontmedium"></label></b>
						</td>
				   </tr>
				   <tr>
						<td>ទឹកប្រាក់ខ្ចីជា(B)​</td>
						<td>:</td>
						<td align="right" style="border:1px solid rgba(156, 158, 159, 1)"><b><label id="lblborrow_bath" class="fontmedium"></label><label id="lblrate_bath" class="fontmedium"></label></b></td>
				   </tr>
				   <tr>
						<td>ទឹកប្រាក់ខ្ចីជា(៛)​</td>
						<td>:</td>
						<td align="right" style="border:1px solid rgba(156, 158, 159, 1)"><b><label id="lblborrow_riel" class="fontmedium"></label><label id="lblrate_riel" class="fontmedium"></label></b></td>
				   </tr>
				    <tr>
						<td>អត្រាការប្រាក់រួម</td>
						<td>:</td>
						<td align="right" style="border:1px solid rgba(156, 158, 159, 1)"><b><label id="lbllaon_rate" class="fontmedium"></label></b></td>
				   </tr>
				    <tr>
						<td colspan="3" align="center" style="border-top:1px solid #000;">
							<label>
								<?php echo $this->keycode['rpt-transfer-warnning-kh'];?>
							</label>
						</td>			
				   </tr>
				   <tr>
						<td colspan="3" align="center" style="border-top:2px dashed #000;padding-top:5px;">
								<?php echo $this->keycode['comment'];?>
						</td>			
				   </tr>
				   <tr>
						<td colspan="3">
							<hr style="background: transparent; border-left:  none;	border-right: none;	border-top:   none;
								border-bottom: 2px dashed #000;" />
						</td>			
				   </tr>
				   <tr>
						<td>
							<img src="<?php echo $base_url.$this->keycode['imgPath'];?>" width="50%"/>
						</td>	
						<td align='right'  valign="top" colspan="2">
							<?php echo date("d/m/Y H:i:s");?>
						</td>
				   </tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" data-dojo-props="title:'បន្ថែមអ្នកខ្ចី'" id="popupsender" >
		<form id="submit_sender" dojoType="dijit.form.Form">
			<table width="400px">
				<tr>
					<td>ឈ្មោះអ្នកខ្ចី</td>
					<td>
						<input type="text" name="sender_name" id="sender_name" required="true" placeholder="ឈ្មោះ​អ្នក​ខ្ចី" class='fullside'
									dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ខ្ចី!" /></td>
				</tr>
				<tr>
					<td>លេខ​ទូរស័ព្ទ​​អ្នក​​ខ្ចី</td>
					<td>
						<input type="text" name="sender_tel" id="sender_tel" placeholder="លេខ​ទូរស័ព្ទ​​អ្នក​​ខ្ចី"  
								 data-dojo-Type="dijit.form.ValidationTextBox"   
								data-dojo-props="regExp:'[0-9]{9,10}', 
												 invalidMessage:'លេខ​ទូរស័ព្ទ​​ មិន​ត្រឹម​ត្រូវទេ. មិនមាន​  ចន្លោះ ឬ សញ្ញា​ពិសេស.',
												 class:'fullside'"/>
					</td>
				</tr>
				<tr>
					<td>អាស័យដ្ឋាន</td>
					<td>
						<input id="address" data-dojo-Type="dijit.form.TextBox" data-dojo-props="name:'address',class:'fullside',style:'height:50px'" />
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center"><br />
						<input type="button" value="រក្សាទុក" label="រក្សាទុក" dojoType="dijit.form.Button" 
					 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="saveSender()"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" data-dojo-props="title:'បញ្ជីជំពាក់ប្រាក់'" id="popuprpt_dabt" >
	<div id="divPrint1" style="padding: 0px; margin: 0px;">
		<form id="submit_sender" >
				<center><b>របាយការណ៏ជំពាក់ត្រឹម <?php echo date('d-M-Y');?></b></center>
			<table id="show_rpt" width="900px" border="1" style="border-collapse: collapse;">
			</table>
						<br /><br />
						<input type="button" value="រក្សាទុក" label="រក្សាទុក" id="asdfsad" dojoType="dijit.form.Button" 
					 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="printReport();"/>
		</form>
	</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl()?>/js/pdbs_js.js" type="text/javascript" > </script>
<script src="<?php echo $this->baseUrl()?>/js/jquery-1.8.2.min.js" type="text/javascript"></script>
<script>
remain_dollar='';
remain_bath='';
remain_riel='';		
withdraw_dollar='';
withdraw_bath=''
withdraw_riel='';
function showDialog() {	
	
	//money_borrow = dijit.byId('amount_borrow').get('value');
	sender = dijit.byId("sender").get('value');
	if(sender <=0 || isNaN(sender)){
		alert('សូម​ជ្រើសរើសឈ្មោះអ្នកខ្ចី...!');
		dijit.byId('sender').focus();
		return false;
	}
	/*if((money_borrow <=0) || (isNaN(money_borrow))){
		alert('សូម​ពិនិត្រ ទឹកប្រាក់​​ដែល​​ត្រូវខ្ចីម្តងទៀត...!');
		dijit.byId('amount_borrow').focus();
		return false;
	}*/
	


	dojo.byId("lblsendername").innerHTML = 
	dojo.byId("lblphone").innerHTML =sender_tel; 
//	dojo.byId("lblmoney_type").innerHTML = dijit.byId("type_money").attr('displayedValue');
	
	borrow_dollar = dijit.byId('borrow_dollar').get('value');
	borrow_bath = dijit.byId('borrow_bath').get('value');
	borrow_riel = dijit.byId('borrow_riel').get('value');

	interest_dollar='';
	interest_bath='';
	interest_riel='';
	if(!isNaN(borrow_dollar)){
		dojo.byId("lblborrow_dollar").innerHTML = dojo.number.format(borrow_dollar);
		interest_dollar=dijit.byId('interest_dollar').get('value');
		if(isNaN(interest_dollar)){
			interest_dollar=0+'%';
		}else{ interest_dollar=interest_dollar+'%';}
	}
	if(!isNaN(borrow_bath)){
		dojo.byId("lblborrow_bath").innerHTML = dojo.number.format(borrow_bath);
		interest_bath=dijit.byId('interest_bath').get('value');//test if rate =blank
		if(isNaN(interest_bath)){
			interest_bath=0+'%';
		}else{ interest_bath=interest_bath+'%'; }
	}
	if(!isNaN(borrow_riel)){
		dojo.byId("lblborrow_riel").innerHTML = dojo.number.format(borrow_riel);
		interest_riel=dijit.byId('interest_riel').get('value')+' %';
		if(isNaN(interest_riel)){
			interest_riel=0+'%';
		}else{ interest_riel=interest_riel+'%'; }
	}

	laon_rate = dijit.byId('total_interest').get('value');
	if(!isNaN(laon_rate)){
		dojo.byId("lbllaon_rate").innerHTML = laon_rate +' %/ខែ';
	}
	all_interest = dijit.byId("all_interest");
	if(all_interest.checked){
		total_interest=dijit.byId('total_interest').get('value');
		if(isNaN(total_interest)){total_interest=0+'%';
		}else{ total_interest = total_interest+'%';}
		dojo.byId('lbllaon_rate').innerHTML=total_interest;
	}else{
		dojo.byId('lblrate_dollar').innerHTML=' / ការប្រាក់ '+interest_dollar;
	    dojo.byId('lblrate_bath').innerHTML=' / ការប្រាក់ '+interest_bath;
		dojo.byId('lblrate_riel').innerHTML=' / ការប្រាក់ '+interest_riel;
	}
	
	
	
	
	
	var mkh = new Array('មករា', 'កុម្ភៈ', 'មីនា', 'មេសា', 'ឧសភា', 'មិថុនា', 'កក្កដា', 'សីហា', 'កញ្ញា', 'តុលា', 'វិច្ឆិកា', 'ធ្នូរ');
	var d = dojo.byId("loan_date").value.split('/');
	dojo.byId("lblstartdate").innerHTML = d[0] + " " + mkh[(d[1]-1)] +" "+d[2];
	dijit.byId("terms").show();
}
								
function showRptDebt(){
	dijit.byId("popuprpt_dabt").show();
}
var url_add_sender = '<?php echo $this->url(array('module'=>'transfer','controller'=>'index','action'=>'addnewsender')); ?>';//for get payment date of sender 
function saveSender(){
	if(dijit.byId('submit_sender').validate()) {
		 sender_name=dijit.byId('sender_name').get('value');
		 sender_tel=dijit.byId('sender_tel').get('value');
		 address=ijit.byId('address').get('value');
				dojo.xhrPost({
				    url: url_add_sender,	
				    content : { 
					    'sender_name': sender_name,
					    'sender_tel': sender_tel,
					    'address': address,
					   	'acc_no':'',
					    'sender_type': 2,
					},		    
					handleAs:"json", 
				    load: function(response) {	
						  if(response==-1){
							   alert('ឈោ្មះ  '+sender_name+' មានរួចហើយ !');
						  }else{
					    	var Newsender = {		
					    			id: response.sender_id,
									name: sender_name,
									acc_code:response.acc_no,
									tel:sender_tel
							};	
							addDataToSelectbox(dijit.byId('sender'), sender_store, Newsender, response.sender_id);
							dijit.byId("popupsender").hide();
					    }
				    },
				    error: function(e) {
					    alert(e);
					    alert("You can not add new sender !");
				    }
				}); 
	}
}
</script>