<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
	
</script>

<form action="<?php echo $this->url(array('module'=>'agent','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="10" width="100%" style="font-size: 15px">
		<tr>
			<td>
				<fieldset>
					<legend style="font-size: 17px"><strong>ដកលុយ</strong></legend>
						<table cellspacing="10"  width="100%" style="font-size: 15px">
						    <tr>
						        <td>លេខគណនី</td>
						        <td><?php echo $form->getElement('nuber_account');?></td>
						        <td></td>
						        <td></td>
						    </tr>
						     <tr>
						        <td>ឈ្មោះអ្នកអតិជន</td>
						        <td><?php echo $form->getElement('namesend');?></td>
						        <td>ថ្ញៃដកប្រាក់</td>
						        <td><?php echo $form->getElement('daydokmoney');?></td>
						    </tr>
						     <tr>
						        <td>លេខទូរស៏ព</td>
						        <td><?php echo $form->getElement('phong');?></td>
						        <td>សំគាល់</td>
						        <td><?php echo $form->getElement('note');?></td>
						    </tr>
					   </table>
						<fieldset>
						<legend><strong>ប្រាក់ក្នុងគណនីបច្ជប្បន្ន</strong></legend>
						<table cellspacing="10"  cellpadding="0" width="100%" style="font-size: 15px">
							<tr>
								<td>ប្រាក់ជាដុល្លា</td>
								<td><?php echo $form->getElement('d1');?></td>
								<td>ប្រាក់ជាបាត</td>
								<td><?php echo $form->getElement('b1');?></td>
								<td>ប្រាក់ជារៀល</td>
								<td><?php echo $form->getElement('r1');?></td>
							</tr>
	
						</table>
					</fieldset>
					<fieldset>
						<legend><strong>ប្រាក់ក្នុងគណនីបច្ជុប្បន្ន</strong></legend>
						<table cellspacing="10"  cellpadding="0" width="100%" style="font-size: 15px">
							<tr>
								<td>ប្រាក់ជាដុល្លា</td>
								<td><?php echo $form->getElement('d2');?></td>
								<td>ប្រាក់ជាបាត</td>
								<td><?php echo $form->getElement('b2');?></td>
								<td>ប្រាក់ជារៀល</td>
								<td><?php echo $form->getElement('r2');?></td>
							</tr>
	
						</table>
					</fieldset>
					<fieldset>
						<legend>ប្រាក់ក្នុងគណនីបន្ទាប់ពីដក</legend>
						<table cellspacing="10"  cellpadding="0" width="100%" style="font-size: 15px">
							<tr>
								<td>ប្រាក់ជាដុល្លា</td>
								<td><?php echo $form->getElement('d3');?></td>
								<td>ប្រាក់ជាបាត</td>
								<td><?php echo $form->getElement('b3');?></td>
								<td>ប្រាក់ជារៀល</td>
								<td><?php echo $form->getElement('r3');?></td>
							</tr>
	
						</table>
					</fieldset>
						
				</fieldset>
				
			</td>			
		</tr>
		
		
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


