<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>

<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
	
</script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<form action="<?php echo $this->url(array('module'=>'partner','controller'=>'withdraw','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="10" width="100%" style="font-size: 15px">
		<tr>
			<td>
				<fieldset>
					<legend style="font-size: 17px"><strong>ពត៏មានដកប្រាក់</strong></legend>
						<table cellspacing="10"  width="100%" style="font-size: 15px">
						    <tr>
						        <td>លេខគណនី</td>
						        <td><?php echo $form->getElement('nuber_account');?></td>
						        <td></td>
						        <td></td>
						    </tr>
						     <tr>
						        <td>ឈ្មោះអតិជន</td>
						        <td><?php echo $form->getElement('namesend');?></td>
						        <td>ថ្ងៃដកប្រាក់</td>
						        <td><?php echo $form->getElement('daydokmoney');?></td>
						    </tr>
						     <tr>
						        <td>លេខទូរស័ព្ទ</td>
						        <td><?php echo $form->getElement('phong');?></td>
						        <td>សម្គាល់</td>
						        <td><?php echo $form->getElement('note');?></td>
						    </tr>
					   </table>
						<fieldset>
						<legend><strong>ប្រាក់ក្នុងគណនីបច្ចុប្បន្ន</strong></legend>
						<table cellspacing="10"  cellpadding="0" width="100%" style="font-size: 15px">
							<tr>
								<td>ប្រាក់ជាដុល្លា</td>
								<td><?php echo $form->getElement('curr_dollar');?></td>
								<td>ប្រាក់ជាបាត</td>
								<td><?php echo $form->getElement('curr_bath');?></td>
								<td>ប្រាក់ជារៀល</td>
								<td><?php echo $form->getElement('curr_riel');?></td>
							</tr>
	
						</table>
					</fieldset>
					<fieldset>
						<legend><strong>ប្រាក់ត្រូវដកពីគណនី</strong></legend>
						<table cellspacing="10"  cellpadding="0" width="100%" style="font-size: 15px">
							<tr>
								<td>ប្រាក់ជាដុល្លា</td>
								<td><?php echo $form->getElement('withdraw_dollar');?></td>
								<td>ប្រាក់ជាបាត</td>
								<td><?php echo $form->getElement('withdraw_bath');?></td>
								<td>ប្រាក់ជារៀល</td>
								<td><?php echo $form->getElement('withdraw_riel');?></td>
							</tr>
	
						</table>
					</fieldset>
					<fieldset>
						<legend>ប្រាក់សល់បន្ទាប់ពីដក</legend>
						<table cellspacing="10"  cellpadding="0" width="100%" style="font-size: 15px">
							<tr>
								<td>ប្រាក់ជាដុល្លា</td>
								<td><?php echo $form->getElement('remain_dollar');?></td>
								<td>ប្រាក់ជាបាត</td>
								<td><?php echo $form->getElement('remain_bath');?></td>
								<td>ប្រាក់ជារៀល</td>
								<td><?php echo $form->getElement('remain_riel');?></td>
							</tr>
	
						</table>
					</fieldset>
						
				</fieldset>
				
			</td>			
		</tr>
		
		
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>
<script type="text/javascript">
<!--
from=0;
to=0;
function CalculateWithdraw_dollar(){
	curr_dollar = dijit.byId('curr_dollar').get('value');
	withdraw_dollar = dijit.byId('withdraw_dollar').get('value');
	remain = curr_dollar-withdraw_dollar;
	dijit.byId('remain_dollar').attr('value',remain);
}

function CalculateWithdraw_bath(){
	curr_bath = dijit.byId('curr_bath').get('value');
	withdraw_bath = dijit.byId('withdraw_bath').get('value');
	remain = curr_bath-withdraw_bath;
	dijit.byId('remain_bath').attr('value',remain);
}

function CalculateWithdraw_riel(){
	curr_riel = dijit.byId('curr_riel').get('value');
	withdraw_riel = dijit.byId('withdraw_riel').get('value');
	remain = curr_riel-withdraw_riel;
	dijit.byId('remain_riel').attr('value',remain);
}
//-->
</script>


