<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Keeping_dokmoney"));
     $frm = $this->frm_partner;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'Keeping','controller'=>'outmoney','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   <td><?php  echo $frm->getElement("adv_search");?></td>
		   <td><?php  echo $frm->getElement('namesend');?></td>
		   <td><?php  echo $frm->getElement("start_date")?></td>
		   <td><?php  echo $frm->getElement("end_date")?></td>
		   <td><?php  echo $frm->getElement('status_search');?></td>
		   <td><?php  echo $frm->getElement("btn_search");?></td>
	   </tr>
   </table>
   
</form>
<?php 
   echo $this->list;
?>
