<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.CheckBox");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>

<form action="<?php echo $this->url(array('module'=>'NewTest','controller'=>'New','action'=>'Testting')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="1" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend style="font-size: 18px; font-family:'Khmer OS Muol'; color: black;"><strong>ពត័មានរបស់សិស្ស </strong></legend>
					<table width="100%" style="font-size: 18px; font-family:'Khmer OS Battambang';">
						<tr>
							<td>id</td>
							<td><?php echo $form->getElement('IdS');?></td>
							<td>Student_name</td>
							<td><?php echo $form->getElement('Student_names');?></td>
							<td>Date_of_birth</td>
							<td><?php echo $form->getElement('Date_of_births');?></td>
						</tr>
						<tr>
							<td>Sex</td>
							<td><?php echo $form->getElement('Sexs');?></td>
							<td>phone</td>
							<td><?php echo $form->getElement('phones');?></td>
							<td>title</td>
							<td><?php echo $form->getElement('titles');?></td>
						</tr>
						
					</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


