<title>3PC System | Add User</title>
<?php $form=$this->form; ?>
<style>
fieldset.fifthy {	
	border-right: 0px;
	width: 50%;	
}
table.user td{
	vertical-align: top;
	padding-left: 5px;	   
}
</style>       
<script language="javascript">
      var temp=-1;
   
	function validateUser(field)
	{
		if(temp==1) return '* User name already exist!';
		else temp==-1;
	}
    function validatePassword(field)
	{
    	var com=$('#confirm_password').val();
    	var pwd=$('#password').val();
		if(com!=pwd) return '* Password mismatch!';		 
	}
</script>
<script type="text/javascript">
	jQuery(Document).ready(function(){
		//binds form submission and fields to the validation engine
		jQuery('#frm').validationEngine('attach', {promptPosition : "centerRight"});
		
	});
</script>
<?php 
	Application_Model_Decorator::removeAllDecorator($form);
	$cancel_url=$this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'user',
		'action'=>'index',
	)); 	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<br/>
<form id="frm" action="<?php echo $form->getAction(); ?>" method="post" enctype="application/x-www-form-urlencoded" >	
	<div class="btn" align="right">
		    <button type="submit" class="positive" name="save">
		        <img src="<?php echo BASE_URL?>/images/icon/apply2.png" alt=""/>
		        <?php echo $tr->translate('SAVE');?>
		    </button>												   						
		    <a href="<?php echo $cancel_url; ?>" class="negative">
		        <img src="<?php echo BASE_URL?>/images/icon/cross.png" alt=""/>
		        <?php echo $tr->translate('CANCEL');?>
		    </a>
   </div>
   <fieldset>
		<legend><?php echo $tr->translate('AUTHENTICATION');?></legend>
		<table>
			<tr>
				<td class="field"><?php echo $tr->translate('GENDER_TITLE');?></td>
				<td class="add-edit"><?php echo $form->getElement('title');?></td>				
			</tr>
			<tr>
				<td class="field"><?php echo $tr->translate('FULL_NAME');?></td>
				<td class="add-edit"><?php echo $form->getElement('name');?></td>				
			</tr>
			<tr>
				<td class="field"><?php echo $tr->translate('CSO');?></td>
				<td class="add-edit"><?php echo $form->getElement('cso_id');?></td>				
			</tr>								
			<tr>
				<td class="field"><?php echo $tr->translate('USERNAME');?></td>
				<td class="add-edit"><?php echo $form->getElement('username');?></td>				
			</tr>
			<tr>
				<td class="field"><?php echo $tr->translate('EMAIL');?></td>
				<td class="add-edit"><?php echo $form->getElement('email');?></td>				
			</tr>			
			<tr>
				<td class="field"><?php echo $tr->translate('PASSWORD');?></td>
				<td class="add-edit"><?php echo $form->getElement('password');?></td>				
			</tr>
			<tr>
				<td class="field"><?php echo $tr->translate('RE_PASSWORD');?></td>
				<td class="add-edit"><?php echo $form->getElement('confirm_password');?></td>				
			</tr>
			<tr>
				<td class="field"><?php echo $tr->translate('TYPE_OF');?></td>
				<td class="add-edit"><?php echo $form->getElement('user_type_id');?></td>				
			</tr>
		</table>
	</fieldset>					
</form>