<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("partner"));
$frm = $this->frm_partner;
// echo $frm;exit();
//print_r($this->result['district_id']);exit();
?>

<form id="list" name="list" action="<?php echo $this->url(array('module'=>'Keeping','controller'=>'customer','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   <td><?php echo $frm->getElement("adv_search");?></td>
		   <td><?php echo $frm->getElement('main_branch');?></td>
		   <td><?php echo $frm->getElement('start_date');?></td>
		   <td><?php echo $frm->getElement('end_date');?></td>
		   <td><?php echo $frm->getElement('status_search');?></td>
		   
		</tr>
		<tr>
				<td><?php echo $frm->getElement('province_name')?></td>
				<td><input id="district" ></td>
		     	<td><input id="commune" ></td>
		      	<td><input id="village" ></td>
		   <td><?php echo $frm->getElement("btn_search");?></td>
	   </tr>
   </table>
   <?php echo $this->list;?>
</form>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
dojo.require("dijit.form.SimpleTextarea");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.RadioButton");
dojo.ready(function(){
	dijit.byId('province_name').attr('value',<?php echo $this->result['province_id'];?>);
	var district_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->district));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: district_data}),
	autoComplete: true,
	query: {
		pro_id: "-1"
		//pro_id:"<?php //echo $this->result['province_id'];?>"
	},            
	required: false,		           
	name: "district",
	id: "district",
	searchAttr: "name",
	value: "<?php echo $this->result['district_id'];?>",
//	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
				filterCommune();
	    }
	}, "district");

	var commune_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->commune_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: commune_data}),
	autoComplete: true,
	query: {
		//district_id: "-1"
		district_id: "<?php echo $this->result['district_id'];?>"
	},            
	required: false,		           
	name: "commune",
	id: "commune",
	searchAttr: "name",
	value: "<?php echo $this->result['comm_id'];?>",
	//class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			filterVillage();
  }
	}, "commune");

	var village_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->village_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: village_data}),
	autoComplete: true,
	query: {
		//commune_id:"-1"
		commune_id:"<?php echo $this->result['comm_id'];?>"
	},            
	required: false,		           
	name: "village",
	id: "village",
	searchAttr: "name",
	//class: 'fullside',
	value: "<?php echo $this->result['village'];?>",
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
}
	}, "village");

	

	
});
function filterDistrict(){
	dijit.byId('district').query.pro_id = dijit.byId('province_name').get('value');
}
function filterCommune(){
	dijit.byId('commune').query.district_id = dijit.byId('district').get('value');
}
function filterVillage(){
	dijit.byId('village').query.commune_id = dijit.byId('commune').get('value');
}

</script>