<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("partner"));
$frm = $this->frm_partner;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'Keeping','controller'=>'Customer','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   <td><?php echo $frm->getElement("adv_search");?></td>
		   <td><?php echo $frm->getElement('main_branch');?></td>
		   <td><?php echo $frm->getElement('status_search');?></td>
		   <td><?php echo $frm->getElement("btn_search");?></td>
		   <?php echo $this->list;?>
	   </tr>
   </table>
</form>
<?php 
   echo $this->list;
?>
