3<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>

<form action="<?php echo $this->url(array('module'=>'Currency','controller'=>'Currensy','action'=>'Curren')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="1" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend style="font-size: 18px; font-family:'Khmer OS Muol'; color: black;"><strong>ពត័មាន ទំនាក់ទំនង របស់​ភ្នាក់ងារ</strong></legend>
						<table width="100%" style="font-size: 18px; font-family:'Khmer OS Battambang';">
							<tr>
								<td>id</td>
								<td><?php echo $form->getElement('ids')?></td>
								<td>search</td>
								<td><?php echo $form->getElement('searchs')?></td>
								<td>add</td>
								<td><?php echo $form->getElement('adds')?></td>
							</tr>
							<tr>
								<td>exit</td>
								<td><?php echo $form->getElement('exits')?></td>
								<td>start</td>
								<td><?php echo $form->getElement('starts')?></td>
								<td>stop</td>
								<td><?php echo $form->getElement('stops')?></td>
								
							</tr>
					</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


