<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_expense;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'expense','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside' >
  
	<tr>
		<td>
				<fieldset>
					<legend><strong>ចំណាយ</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
						    
							    <?php echo $frm->getElement('id');?>
							<td><?php echo $tr->translate("Expense Name")?></td>
							<td><?php echo $frm->getElement('account_name');?></td>
							<td><?php echo $tr->translate("Date")?></td>
							<td><?php echo $frm->getElement('Date');?></td>
							
							
						</tr>
						<tr>
						    <td><?php echo $tr->translate("Total amount")?></td>
							<td><?php echo $frm->getElement('total_amount');?></td>
							<td><?php echo $tr->translate("Currency type")?></td>
				            <td><?php echo $frm->getElement('currency_type');?></td>
						   
							
						</tr>
						<tr>
						    <td><?php echo $tr->translate("Description")?></td>
						    <td><?php echo $frm->getElement('Description');?></td>
						    <td><?php echo $tr->translate("Fordate")?></td>
							<td><?php echo $frm->getElement('for_date');?></td>
						</tr>
						<tr>
						   <td><?php echo $tr->translate("Stutas")?></td>
				           <td><?php echo $frm->getElement('Stutas');?></td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
		     <input type="reset" value="សំអាត" label="សំអាត" id="" dojoType="dijit.form.Button"
				 iconClass=""/>
			 <input type="submit" value="save_close" name="save_close" label="រក្សាទុក&ចាកចេញ" id="" dojoType="dijit.form.Button"
				 iconClass=""/>
				 
			<input type="submit" value="save" name="save" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
				 
		   <input type="submit" value="cancel" name="cancel" label="ចាកចេញ" id="" dojoType="dijit.form.Button"
				 iconClass=""/>
		   
		</td>
	</tr>	
</table>
</form>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
</script>
