<title>Expense List</title>
<?php 
   $frm=$this->frm_expense;
?>

<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'expense','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<table>
		<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('status_search');?></td>
			<td><?php echo $frm->getElement('for_date_search');?></td>
			<td><?php echo $frm->getElement('btn_search');?></td>
		</tr>
	</table>
   <?php echo $this->list;?>
</form>
