<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require("dijit.form.TextBox");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>

<form action="<?php echo $this->url(array('module'=>'Payroll','controller'=>'Index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="0" width="100%" >
		<tr>
			<td>
				<fieldset>
					<legend><strong>ពត៏មានប្រាក់ខែរ</strong></legend>
						<table  width="100%">
							<tr>
								<td>ឈ្មោះបុក្គលិក</td>
								<td ><?php echo $form->getElement('staff_name');?></td>
								<td>ភេទ</td>
								<td><?php echo $form->getElement('Sex');?></td>
								<td>មុខងារ</td>
								<td><?php echo $form->getElement('position');?></td>
							</tr>
							<tr>
								<td>ប្រាក់ខែគោល</td>
								<td><?php echo $form->getElement('Basic_salary');?></td>
								<td>ប្រចាំខែរ</td>
								<td><?php echo $form->getElement('for_manth');?></td>
								<td>ថ្ងៃចូល</td>
								<td><?php echo $form->getElement('Start_day');?></td>
							</tr>
					</table>
				</fieldset>
				
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


