<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	
</script>

<form action="<?php echo $this->url(array('module'=>'agent','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="10" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend align="right">ពត័មាន ​ដកប្រាក់</legend>
						<table cellspacing="5" cellpadding="0" width="100%">
						
		​​​​<tr>
		​​​​	<td>
		​​		<fieldset>
					<legend align="right">ប្រាក់ក្នុងគណនីបច្ចុប្បន្ន</legend>
						<table cellspacing="5" cellpadding="0" width="100%">
						
						<tr>
						 <td>ប្រាក់ជាដុល្លា</td>
						 <td><?php echo $form->getElement('dola3');?></td>
						 <td>ប្រាក់ជាបាត</td>
						 <td><?php echo $form->getElement('bath3');?></td>
						​ <td>ប្រាក់ជារៀល</td>
						​​​​​<td><?php echo $form->getElement('real3');?></td>​​​​​
						</tr>
						</table>
				</fieldset>
	        </td>			
		</tr>
		<table cellspacing="10" width="100%">
		​​​​<tr>
		​​​​	<td>
		​​		<fieldset>
					<legend align="right">ប្រាក់ត្រូវដកពីគណនី</legend>
						<table cellspacing="5" cellpadding="0" width="100%">
						
						<tr>
						 <td>ប្រាក់ជាដុល្លា</td>
						 <td><?php echo $form->getElement('dola4');?></td>
						 <td>ប្រាក់ជាបាត</td>
						 <td><?php echo $form->getElement('bath4');?></td>
						​ <td>ប្រាក់ជារៀល</td>
						​​​​​<td><?php echo $form->getElement('real4');?></td>​​​​​
						</tr>
						</table>
				</fieldset>
	</td>			
		</tr>
			<table cellspacing="10" width="100%">
		​​​​<tr>
		​​​​	<td>
		​​		<fieldset>
					<legend align="right">ប្រាក់ក្នុងគណនីបន្ទាប់ពីដក</legend>
						<table cellspacing="5" cellpadding="0" width="100%">
						
						<tr>
						 <td>ប្រាក់ជាដុល្លា</td>
						 <td><?php echo $form->getElement('dola5');?></td>
						 <td>ប្រាក់ជាបាត</td>
						 <td><?php echo $form->getElement('bath5');?></td>
						​ <td>ប្រាក់ជារៀល</td>
						​​​​​<td><?php echo $form->getElement('real5');?></td>​​​​​
						</tr>
						</table>
				</fieldset>
				</td>			
		</tr>
</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


