<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;

?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'index','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>បន្ថែមលុយ​ ទៅកន្លែងគិតលុយ</strong></legend>
					<table cellspacing="10"  width="100%">
					    <tr>
							<td>ឈ្មោះបុគ្គលិក</td>
							   <?php echo $frm->getElement('id')?>
							<td><?php echo $frm->getElement('name_staff')?></td>
							<td>លេខសំគាល់ខ្លួន</td>
							<td><?php echo $frm->getElement('ids')?></td>
							<td>Date</td>	
							<td><?php echo $frm->getElement('date')?></td>
							
						</tr>
						<tr>
						    <td>ដុល្លា</td>
							<td><?php echo $frm->getElement('usa')?></td>
							<td>បាត</td>	
							<td><?php echo $frm->getElement('bath')?></td>
						    <td>រៀល</td>
							<td><?php echo $frm->getElement('reil')?></td>
							
						</tr>
						<tr>
						    <td>សំគាល់</td>
							<td><?php echo $frm->getElement('note')?></td>
							<td>Status</td>
							<td><?php echo $frm->getElement('status')?></td>
						</tr>
						<tr>
							
							
						</tr>
					</table>
				</fieldset>
				
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="Update" id="submitButton1" dojoType="dijit.form.Button" 
			 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.DateTextBox");
</script>
<script type="text/javascript">
   function setId(){
	   client_id = dijit.byId('name_staff').get('value');
	   dijit.byId("ids").attr('value',client_id);	   
 }
   function setName(){
	   client_id = dijit.byId('ids').get('value');
	  // alert(client_id);
	   dijit.byId("name_staff").attr('value',client_id);	   
 }
</script>