<?php
	$this->headTitle('Currency Smart | Exchange add page'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<style>
<!--
	.tbtable{		
		text-align: center;
		font-size: 2em;	
		color: #fff;
		line-height: 40px;
		font-weight: bolder;
	}
	.tbtable td{
		vertical-align: middle;
	}
	.tbtable .tbheader{
		background-color: #dddddd;
		color: #000;
	}
	.tbtable .first{
		background-color: #012a15; 
	}
	
	.tbtable .second{
		background-color: #016315; 
	}
	
	.tbtable .input-inner {
		margin: 0px;
		padding: 0px;
		width: 99%;	
		border: none;
	}
	
	#DB.dijitInputInner, #BD.dijitInputInner, #BR.dijitInputInner,#RB.dijitInputInner{
		text-align: center;		
		background-color: #012a15 !important;
	}
	
	#DR.dijitInputInner, #RD.dijitInputInner{
		text-align: center;		
		background-color: #016315 !important;
	}
	
	.col-symbol{
		width: 20%;
	}
	.col-input{
		width: 40%;
	}
-->
</style>
<form id='frm_add_exch' action="<?php echo $this->url(array('module'=>'exchange','controller'=>'index','action'=>'rate')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>	 
	
	<table cellspacing="20" width="100%"  >
		<tr>
			<td width="100%" valign="top">	
				<fieldset class="panel">
					<legend><strong>ព៌ត័មាន ទាក់​ទង នឹង​ អត្រាការប្រាក់</strong></legend>			
					<table class="tbtable" style="margin:10px auto; width: 90%;" cellspacing='0' border="1">									
						<tr class="tbheader">
							<th class="col-symbol">និមិត្តសញ្ញា</th>
							<th class="col-input">អត្រា​ទិញចូល</th>
							<th class="col-input">អត្រា​លក់ចេញ</th>
						</tr>
						<tr class="first">
							<td>$ - B</td>
							<td>
								<input type="text" name="DB" id="DB"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'DB',
									id:'DB',	
									class:'input-inner',								
									value:<?php echo $this->ratelist['DB']?>,
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
							</td>
							<td>
								<input type="text" name="BD" id="BD"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'BD',
									id:'BD',	
									class:'input-inner',								
									value:<?php echo $this->ratelist['BD']?>,
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
							</td>
						</tr>
						<tr class="second">
							<td>$ - R</td>
							<td>
								<input type="text" name="DR" id="DR"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'DR',
									id:'DR',	
									class:'input-inner',								
									value:<?php echo $this->ratelist['DR']?>,
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
							</td>
							<td>
								<input type="text" name="RD" id="RD"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'RD',
									id:'RD',	
									class:'input-inner',								
									value:<?php echo $this->ratelist['RD']?>,
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
							</td>
						</tr>
						<tr class="first">
							<td>B - R</td>
							<td>
								<input type="text" name="BR" id="BR"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'BR',
									id:'BR',	
									class:'input-inner',								
									value:<?php echo $this->ratelist['BR']?>,
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
							</td>
							<td>
								<input type="text" name="RB" id="RB"  data-dojo-type="dijit.form.NumberTextBox"
									data-dojo-props="required:true,																		
									name:'RB',
									id:'RB',	
									class:'input-inner',								
									value:<?php echo $this->ratelist['RB']?>,
									constraints:{pattern:'#,###.##'},
									missingMessage:'អ្នក​ភ្លេច​បំពេញ​ ចំនួន​ទឹក​ប្រាក់!',
									invalidMessage:'ចំនួន​ទឹក​ប្រាក់​ មិន​ត្រឹម​ត្រូវ!'">
							</td>
						</tr>
					</table>
					<div style="text-align: center; margin: 10px 0px;">
						<input type="button" value="សំអាត" label="សំអាត" id="clearButton" onclick="clearText();" dojoType="dijit.form.Button"/>
						<input type="reset" value="សាដើម" label="សាដើម" id="resetButton" dojoType="dijit.form.Button"/>
						<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  />	
					</div>	
				</fieldset>
			</td>
						
		</tr>		
	</table>
</form>

<script type="text/javascript">
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');

	function clearText(){
		dojo.byId("DB").value = 0;
		dojo.byId("BD").value = 0;
		dojo.byId("DR").value = 0;
		dojo.byId("RD").value = 0;
		dojo.byId("BR").value = 0;
		dojo.byId("RB").value = 0;		
	}
</script>