<?php
	$this->headTitle('Currency Smart | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");

	dojo.require("dijit.form.CheckBox");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>

<form action="<?php echo $this->url(array('module'=>'agent','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="1" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend style="font-size: 18px; font-family:'Khmer OS Muol'; color: black;"><strong>ព៌ត័មាន បើកប្រាក់ខែរ</strong></legend>
					<table width="100%" style="font-size: 18px; font-family:'Khmer OS Battambang';">
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>ការប្រាក់រួម<?php echo $form->getElement('total_interest');?></td>
							<td><?php echo $form->getElement('total_interested');?></td>
						</tr>
						<tr>
							<td>ឈ្មោះអ្មកខ្ចី</td>
							<td><?php echo $form->getElement('borrower');?></td>
							<td>ចំនួនទឹកប្រាក់ខ្ចី($)</td>
							<td><?php echo $form->getElement('borrow_dollar');?></td>
							<td>ការប្រាក់($)(%ខែរ)</td>
							<td><?php echo $form->getElement('interest_dollar');?></td>
						</tr>
						<tr>
							<td>លេខទូរស័ព្ទ</td>
							<td><?php echo $form->getElement('phone_number');?></td>
							<td>ចំនួនទឹកប្រាក់ខ្ចី(B)</td>
							<td><?php echo $form->getElement('Start_day');?></td>
							<td>ការប្រាក់(B)(%ខែរ)</td>
							<td><?php echo $form->getElement('interest_bath');?></td>
						</tr>
						<tr>
							<td>ថ្ងៃខ្ចីប្រាក់</td>
							<td><?php echo $form->getElement('loan_date');?></td>
							<td>ចំនួនទឹកប្រាក់ខ្ចី(R)</td>
							<td><?php echo $form->getElement('borrow_rail');?></td>
							<td>ការប្រាក់(R)(%ខែរ)</td>
							<td><?php echo $form->getElement('interest_rail');?></td>
						</tr>
					</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>


