<?php
	$this->headTitle('Currency Smart | Add Money Stock'); 
	echo $this->headTitle();
	$session_user=new Zend_Session_Namespace('auth');
	$form = $this->frm;
?>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
<script type="text/javascript">
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.html");
	dojo.ready(function(){
		addAmountTypeMoney();		
	});  
	    
</script>
<style>
<!--
	.tbtable{		
		font-weight: bolder;
		line-height: 40px;
		text-align: center;
	}
	.tbtable .tbheader{
		background-color: #012a15;
		text-align: left;
		color: #fff;
	}
	.tbtable .first{
		background-color: #016315;
		color: #fff;
	}
	.tbtable .first td{
		width: 33.33%
	}
	.tbtable .second{
		background-color: #fff; 
		color: black;
	}
	.nevg-value{
		color: RED;
	}
	.tbtable .second .input-inner {
		margin: 0px;
		padding: 0px;
		width: 99%;	
		border: none;
	}
	#dollar.dijitInputInner, #bath.dijitInputInner, #rail.dijitInputInner{
		text-align: center;		
		background-color: #FFFFFF !important;
	}
	.bg-white{
		background-color: #FFFFFF !important;		
	}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
}
.smallsize{ width:20% !important;}
</style>
<form action="<?php echo $this->url(array('module'=>'partner','controller'=>'Deposite','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
	<table  cellspacing="10" width="100%">
		<tr>
			<td>=
				<fieldset>
					<legend ><strong>ព៌ត័មាន ដៃគូរ</strong></legend>
						<table cellspacing="5" cellpadding="0" width="100%">
							<tr>
								<td>លេខគណនី</td>
								<td width="20%"><?php echo $form->getElement('accourn_number');?></td>
								<td>លេខវិកាប័ត្ត</td>
								<td><?php echo $form->getElement('num_invoice');?></td>
								<td></td>
								<td></td>
								
							</tr>
							<tr>
								<td>ឈ្មោះដៃគូរ</td>
								<td><?php echo $form->getElement('name_partner');?></td>
								<td>កាលបរិច្ឆេត</td>
								<td><?php echo $form->getElement('creat_date');?></td>
								<td>សំគាល់</td>
								<td><?php echo $form->getElement('moneyinaccount');?></td>
							</tr>
								<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" /></td>
					</table>
					<fieldset>
						<legend>ប្រាក់ក្នុងគណនីបច្ចុប្បន្ន</legend>
						<table  cellpadding="0" width="100%">
							<tr>
								<td>ប្រាក់ជាដុល្លា</td>
								<td width="20%"><?php echo $form->getElement('usa');?></td>
								<td>ប្រាក់ជាបាត</td>
								<td><?php echo $form->getElement('bathe');?></td>
								<td>ប្រាក់ជារៀល</td>
								<td><?php echo $form->getElement('reil');?></td>
							</tr>
						</table>
					</fieldset>
				</fieldset>
				<fieldset>
					<legend ><strong>ព៌ត័មាន សាច់ប្រាក់</strong></legend>
						<table cellspacing="5" cellpadding="0" width="100%" >
							<tr>
								<td valign="top">
									<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
									<tr id="head_title" class="head-title" align="center"></tr>
									</table>
								</td>
							</tr>
							<tr style="border:1px solid #ccc !important;">
								<td align="left" valign="top">
									<input id="add-append" value="បន្ថែម" label="បន្ថែម" dojoType="dijit.form.Button" iconClass="dijitIconApplication" Onclick="addAmountTypeMoney();" />
								</td>
							</tr>
					</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>
<form id='frm_add_capital' action="<?php echo $this->url(array('module'=>'partner','controller'=>'deposite','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('doloar').get('value') == 0 && dijit.byId('bath').get('value') == 0 && dijit.byId('rail').get('value') == 0){
					dijit.byId('doloar').focus();
					return false;
				}*/
				return true;
			} else {
				return false;
			}
	</script>	 
	
	<table class="tbtable" style="margin:10px auto; width:100%; border-collapse: collapse; border:1px solid #ccc;" >
		<tr>
			<td width="50%" valign="top">
			 	<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
					<tr id="head_title" class="head-title" align="center"></tr>
				</table>
			</td>
		</tr>
		<tr style="border:1px solid #ccc !important;">
		</tr>
	</table>
</form>
<script type="text/javascript">
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_capital"+ids).remove();
		
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_capital"+index).remove();
	}
}
	curr_dollar_amountoption = '<?php echo $this->currency_type;?>';
	temp='';
	r = 0;
	fund_title=0;
	function addAmountTypeMoney(){
			r++;
			if(fund_title!=1){
				thead='<th>លុប</th>';
				thead+='<th>​ថ្ងៃដាក់ប្រាក់</th>';
				thead+='<th>​ប្រភេទប្រាក់</th>';
				thead+='<th>ប្រាក់ក្នុងគណនី</th>';
				thead+='<th>ប្រាក់បានទទួល</th>';
				thead+='<th>ប្រាក់អាប់</th>';
				thead+='<th>ចំណាំ </th>';
				fund_title=1;
				dojo.query("#head_title").append(thead);
	        }
			temp='<td style="width:30px !important;"><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			temp+='<td><input type="text" required="true" value="<?php echo date('Y-m-d');?>" name="date_'+r+'" id="date_'+r+'" dojoType="dijit.form.DateTextBox"/></td>';
			temp+='<td><select style=" width:70%;" id="currency_type_'+r+'" name="currency_type_'+r+'" dojoType="dijit.form.FilteringSelect">'+curr_dollar_amountoption+'</select></td>';
			temp+='<td><input type="text" onkeyup="calCulateDeposit('+r+');" value="0" style=" width:70%;" required="true" name="amount_'+r+'" id="amount_'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" onkeyup="returnMoney('+r+');" value="0" style=" width:70%;" required="true" name="recieve_'+r+'" id="recieve_'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" style=" width:70%;" value="0" required="true" name="return_'+r+'" id="return_'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" name="note_'+r+'" id="note_'+r+'" dojoType="dijit.form.TextBox" s/></td>';
			tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
			tmp+="</tr>";
				dojo.query("#t_amountmoneytype").append(tmp);
				dojo.html.set(dojo.byId("row_capital"+r),temp, {
			    parseContent: true,
			});
			if(dijit.byId("record_row").value!="") {
				var ids = dijit.byId("record_row").value;
				dijit.byId("record_row").attr('value',ids+','+r);
			} else { dijit.byId("record_row").attr('value',r);}
	}	
//sub money
	sub_title=0;
	s=0;
function calCulateDeposit(index){
	input_amount = dijit.byId('amount_'+index).get('value');
	dijit.byId('recieve_'+index).attr('value',input_amount);
	returnMoney(index);
}
function returnMoney(index){
	input_amount = dijit.byId('amount_'+index).get('value');
	recieve_amount = dijit.byId('recieve_'+index).get('value');
	return_a = recieve_amount-input_amount;
	dijit.byId('return_'+index).attr('value',return_a);
}
</script>